var annotated_dup =
[
    [ "compiler_workarounds", "namespacecompiler__workarounds.html", [
      [ "folder_name_equal", "structcompiler__workarounds_1_1folder__name__equal.html", "structcompiler__workarounds_1_1folder__name__equal" ]
    ] ],
    [ "pstsdk", "namespacepstsdk.html", [
      [ "disk", "namespacepstsdk_1_1disk.html", [
        [ "block_reference", "structpstsdk_1_1disk_1_1block__reference.html", "structpstsdk_1_1disk_1_1block__reference" ],
        [ "root", "structpstsdk_1_1disk_1_1root.html", "structpstsdk_1_1disk_1_1root" ],
        [ "header&lt; ulonglong &gt;", "structpstsdk_1_1disk_1_1header_3_01ulonglong_01_4.html", "structpstsdk_1_1disk_1_1header_3_01ulonglong_01_4" ],
        [ "header&lt; ulong &gt;", "structpstsdk_1_1disk_1_1header_3_01ulong_01_4.html", "structpstsdk_1_1disk_1_1header_3_01ulong_01_4" ],
        [ "header_crc_locations&lt; ulong &gt;", "structpstsdk_1_1disk_1_1header__crc__locations_3_01ulong_01_4.html", null ],
        [ "header_crc_locations&lt; ulonglong &gt;", "structpstsdk_1_1disk_1_1header__crc__locations_3_01ulonglong_01_4.html", null ],
        [ "page_trailer&lt; ulonglong &gt;", "structpstsdk_1_1disk_1_1page__trailer_3_01ulonglong_01_4.html", "structpstsdk_1_1disk_1_1page__trailer_3_01ulonglong_01_4" ],
        [ "page_trailer&lt; ulong &gt;", "structpstsdk_1_1disk_1_1page__trailer_3_01ulong_01_4.html", "structpstsdk_1_1disk_1_1page__trailer_3_01ulong_01_4" ],
        [ "page", "structpstsdk_1_1disk_1_1page.html", "structpstsdk_1_1disk_1_1page" ],
        [ "amap_page", "structpstsdk_1_1disk_1_1amap__page.html", null ],
        [ "pmap_page", "structpstsdk_1_1disk_1_1pmap__page.html", null ],
        [ "fmap_page", "structpstsdk_1_1disk_1_1fmap__page.html", null ],
        [ "fpmap_page", "structpstsdk_1_1disk_1_1fpmap__page.html", null ],
        [ "dlist_page", "structpstsdk_1_1disk_1_1dlist__page.html", "structpstsdk_1_1disk_1_1dlist__page" ],
        [ "bt_entry", "structpstsdk_1_1disk_1_1bt__entry.html", "structpstsdk_1_1disk_1_1bt__entry" ],
        [ "nbt_leaf_entry", "structpstsdk_1_1disk_1_1nbt__leaf__entry.html", "structpstsdk_1_1disk_1_1nbt__leaf__entry" ],
        [ "bbt_leaf_entry", "structpstsdk_1_1disk_1_1bbt__leaf__entry.html", "structpstsdk_1_1disk_1_1bbt__leaf__entry" ],
        [ "bt_page", "structpstsdk_1_1disk_1_1bt__page.html", "structpstsdk_1_1disk_1_1bt__page" ],
        [ "nbt_nonleaf_page", "structpstsdk_1_1disk_1_1nbt__nonleaf__page.html", null ],
        [ "bbt_nonleaf_page", "structpstsdk_1_1disk_1_1bbt__nonleaf__page.html", null ],
        [ "nbt_leaf_page", "structpstsdk_1_1disk_1_1nbt__leaf__page.html", null ],
        [ "bbt_leaf_page", "structpstsdk_1_1disk_1_1bbt__leaf__page.html", null ],
        [ "block_trailer&lt; ulonglong &gt;", "structpstsdk_1_1disk_1_1block__trailer_3_01ulonglong_01_4.html", "structpstsdk_1_1disk_1_1block__trailer_3_01ulonglong_01_4" ],
        [ "block_trailer&lt; ulong &gt;", "structpstsdk_1_1disk_1_1block__trailer_3_01ulong_01_4.html", "structpstsdk_1_1disk_1_1block__trailer_3_01ulong_01_4" ],
        [ "external_block", "structpstsdk_1_1disk_1_1external__block.html", "structpstsdk_1_1disk_1_1external__block" ],
        [ "extended_block&lt; ulonglong &gt;", "structpstsdk_1_1disk_1_1extended__block_3_01ulonglong_01_4.html", "structpstsdk_1_1disk_1_1extended__block_3_01ulonglong_01_4" ],
        [ "extended_block&lt; ulong &gt;", "structpstsdk_1_1disk_1_1extended__block_3_01ulong_01_4.html", "structpstsdk_1_1disk_1_1extended__block_3_01ulong_01_4" ],
        [ "sub_leaf_entry", "structpstsdk_1_1disk_1_1sub__leaf__entry.html", "structpstsdk_1_1disk_1_1sub__leaf__entry" ],
        [ "sub_nonleaf_entry", "structpstsdk_1_1disk_1_1sub__nonleaf__entry.html", "structpstsdk_1_1disk_1_1sub__nonleaf__entry" ],
        [ "sub_block", "structpstsdk_1_1disk_1_1sub__block.html", "structpstsdk_1_1disk_1_1sub__block" ],
        [ "sub_nonleaf_block", "structpstsdk_1_1disk_1_1sub__nonleaf__block.html", null ],
        [ "sub_leaf_block", "structpstsdk_1_1disk_1_1sub__leaf__block.html", null ],
        [ "heap_first_header", "structpstsdk_1_1disk_1_1heap__first__header.html", "structpstsdk_1_1disk_1_1heap__first__header" ],
        [ "heap_page_header", "structpstsdk_1_1disk_1_1heap__page__header.html", "structpstsdk_1_1disk_1_1heap__page__header" ],
        [ "heap_page_fill_header", "structpstsdk_1_1disk_1_1heap__page__fill__header.html", "structpstsdk_1_1disk_1_1heap__page__fill__header" ],
        [ "heap_page_map", "structpstsdk_1_1disk_1_1heap__page__map.html", "structpstsdk_1_1disk_1_1heap__page__map" ],
        [ "bth_header", "structpstsdk_1_1disk_1_1bth__header.html", "structpstsdk_1_1disk_1_1bth__header" ],
        [ "bth_nonleaf_entry", "structpstsdk_1_1disk_1_1bth__nonleaf__entry.html", "structpstsdk_1_1disk_1_1bth__nonleaf__entry" ],
        [ "bth_leaf_entry", "structpstsdk_1_1disk_1_1bth__leaf__entry.html", "structpstsdk_1_1disk_1_1bth__leaf__entry" ],
        [ "bth_node", "structpstsdk_1_1disk_1_1bth__node.html", "structpstsdk_1_1disk_1_1bth__node" ],
        [ "bth_leaf_node", "structpstsdk_1_1disk_1_1bth__leaf__node.html", null ],
        [ "bth_nonleaf_node", "structpstsdk_1_1disk_1_1bth__nonleaf__node.html", null ],
        [ "prop_entry", "structpstsdk_1_1disk_1_1prop__entry.html", "structpstsdk_1_1disk_1_1prop__entry" ],
        [ "sub_object", "structpstsdk_1_1disk_1_1sub__object.html", "structpstsdk_1_1disk_1_1sub__object" ],
        [ "mv_toc", "structpstsdk_1_1disk_1_1mv__toc.html", "structpstsdk_1_1disk_1_1mv__toc" ],
        [ "column_description", "structpstsdk_1_1disk_1_1column__description.html", "structpstsdk_1_1disk_1_1column__description" ],
        [ "gust_column_description", "structpstsdk_1_1disk_1_1gust__column__description.html", "structpstsdk_1_1disk_1_1gust__column__description" ],
        [ "tc_header", "structpstsdk_1_1disk_1_1tc__header.html", "structpstsdk_1_1disk_1_1tc__header" ],
        [ "gust_header", "structpstsdk_1_1disk_1_1gust__header.html", "structpstsdk_1_1disk_1_1gust__header" ],
        [ "nameid", "structpstsdk_1_1disk_1_1nameid.html", "structpstsdk_1_1disk_1_1nameid" ],
        [ "nameid_hash_entry", "structpstsdk_1_1disk_1_1nameid__hash__entry.html", "structpstsdk_1_1disk_1_1nameid__hash__entry" ]
      ] ],
      [ "bth_nonleaf_node", "classpstsdk_1_1bth__nonleaf__node.html", "classpstsdk_1_1bth__nonleaf__node" ],
      [ "bth_leaf_node", "classpstsdk_1_1bth__leaf__node.html", "classpstsdk_1_1bth__leaf__node" ],
      [ "bth_node", "classpstsdk_1_1bth__node.html", "classpstsdk_1_1bth__node" ],
      [ "hid_stream_device", "classpstsdk_1_1hid__stream__device.html", "classpstsdk_1_1hid__stream__device" ],
      [ "heap_impl", "classpstsdk_1_1heap__impl.html", "classpstsdk_1_1heap__impl" ],
      [ "heap", "classpstsdk_1_1heap.html", "classpstsdk_1_1heap" ],
      [ "named_prop", "classpstsdk_1_1named__prop.html", "classpstsdk_1_1named__prop" ],
      [ "name_id_map", "classpstsdk_1_1name__id__map.html", "classpstsdk_1_1name__id__map" ],
      [ "hnid_stream_device", "classpstsdk_1_1hnid__stream__device.html", "classpstsdk_1_1hnid__stream__device" ],
      [ "const_property_object", "classpstsdk_1_1const__property__object.html", "classpstsdk_1_1const__property__object" ],
      [ "property_bag", "classpstsdk_1_1property__bag.html", "classpstsdk_1_1property__bag" ],
      [ "const_table_row", "classpstsdk_1_1const__table__row.html", "classpstsdk_1_1const__table__row" ],
      [ "const_table_row_iter", "classpstsdk_1_1const__table__row__iter.html", "classpstsdk_1_1const__table__row__iter" ],
      [ "table_impl", "classpstsdk_1_1table__impl.html", "classpstsdk_1_1table__impl" ],
      [ "basic_table", "classpstsdk_1_1basic__table.html", "classpstsdk_1_1basic__table" ],
      [ "table", "classpstsdk_1_1table.html", "classpstsdk_1_1table" ],
      [ "database_impl", "classpstsdk_1_1database__impl.html", "classpstsdk_1_1database__impl" ],
      [ "block_info", "structpstsdk_1_1block__info.html", "structpstsdk_1_1block__info" ],
      [ "page_info", "structpstsdk_1_1page__info.html", "structpstsdk_1_1page__info" ],
      [ "node_info", "structpstsdk_1_1node__info.html", "structpstsdk_1_1node__info" ],
      [ "subnode_info", "structpstsdk_1_1subnode__info.html", "structpstsdk_1_1subnode__info" ],
      [ "bt_page", "classpstsdk_1_1bt__page.html", "classpstsdk_1_1bt__page" ],
      [ "bt_nonleaf_page", "classpstsdk_1_1bt__nonleaf__page.html", "classpstsdk_1_1bt__nonleaf__page" ],
      [ "bt_leaf_page", "classpstsdk_1_1bt__leaf__page.html", "classpstsdk_1_1bt__leaf__page" ],
      [ "const_btree_node_iter", "classpstsdk_1_1const__btree__node__iter.html", "classpstsdk_1_1const__btree__node__iter" ],
      [ "db_context", "classpstsdk_1_1db__context.html", "classpstsdk_1_1db__context" ],
      [ "node_impl", "classpstsdk_1_1node__impl.html", "classpstsdk_1_1node__impl" ],
      [ "subnode_transform_info", "classpstsdk_1_1subnode__transform__info.html", "classpstsdk_1_1subnode__transform__info" ],
      [ "node_stream_device", "classpstsdk_1_1node__stream__device.html", "classpstsdk_1_1node__stream__device" ],
      [ "node", "classpstsdk_1_1node.html", "classpstsdk_1_1node" ],
      [ "block", "classpstsdk_1_1block.html", "classpstsdk_1_1block" ],
      [ "data_block", "classpstsdk_1_1data__block.html", "classpstsdk_1_1data__block" ],
      [ "extended_block", "classpstsdk_1_1extended__block.html", "classpstsdk_1_1extended__block" ],
      [ "external_block", "classpstsdk_1_1external__block.html", "classpstsdk_1_1external__block" ],
      [ "subnode_block", "classpstsdk_1_1subnode__block.html", "classpstsdk_1_1subnode__block" ],
      [ "subnode_nonleaf_block", "classpstsdk_1_1subnode__nonleaf__block.html", "classpstsdk_1_1subnode__nonleaf__block" ],
      [ "subnode_leaf_block", "classpstsdk_1_1subnode__leaf__block.html", "classpstsdk_1_1subnode__leaf__block" ],
      [ "page", "classpstsdk_1_1page.html", "classpstsdk_1_1page" ],
      [ "is_nid_type", "structpstsdk_1_1is__nid__type.html", "structpstsdk_1_1is__nid__type" ],
      [ "search_folder", "classpstsdk_1_1search__folder.html", "classpstsdk_1_1search__folder" ],
      [ "search_folder_transform_row", "classpstsdk_1_1search__folder__transform__row.html", "classpstsdk_1_1search__folder__transform__row" ],
      [ "folder_transform_row", "classpstsdk_1_1folder__transform__row.html", "classpstsdk_1_1folder__transform__row" ],
      [ "folder", "classpstsdk_1_1folder.html", "classpstsdk_1_1folder" ],
      [ "folder_transform_info", "classpstsdk_1_1folder__transform__info.html", "classpstsdk_1_1folder__transform__info" ],
      [ "attachment", "classpstsdk_1_1attachment.html", "classpstsdk_1_1attachment" ],
      [ "attachment_transform", "classpstsdk_1_1attachment__transform.html", "classpstsdk_1_1attachment__transform" ],
      [ "recipient", "classpstsdk_1_1recipient.html", "classpstsdk_1_1recipient" ],
      [ "recipient_transform", "structpstsdk_1_1recipient__transform.html", "structpstsdk_1_1recipient__transform" ],
      [ "message", "classpstsdk_1_1message.html", "classpstsdk_1_1message" ],
      [ "message_transform_row", "classpstsdk_1_1message__transform__row.html", "classpstsdk_1_1message__transform__row" ],
      [ "message_transform_info", "classpstsdk_1_1message__transform__info.html", "classpstsdk_1_1message__transform__info" ],
      [ "pst", "classpstsdk_1_1pst.html", "classpstsdk_1_1pst" ],
      [ "btree_iter_impl", "structpstsdk_1_1btree__iter__impl.html", "structpstsdk_1_1btree__iter__impl" ],
      [ "btree_node_nonleaf", "classpstsdk_1_1btree__node__nonleaf.html", "classpstsdk_1_1btree__node__nonleaf" ],
      [ "btree_node", "classpstsdk_1_1btree__node.html", "classpstsdk_1_1btree__node" ],
      [ "btree_node_leaf", "classpstsdk_1_1btree__node__leaf.html", "classpstsdk_1_1btree__node__leaf" ],
      [ "can_not_resize", "classpstsdk_1_1can__not__resize.html", "classpstsdk_1_1can__not__resize" ],
      [ "not_implemented", "classpstsdk_1_1not__implemented.html", "classpstsdk_1_1not__implemented" ],
      [ "write_error", "classpstsdk_1_1write__error.html", "classpstsdk_1_1write__error" ],
      [ "database_corrupt", "classpstsdk_1_1database__corrupt.html", "classpstsdk_1_1database__corrupt" ],
      [ "invalid_format", "classpstsdk_1_1invalid__format.html", "classpstsdk_1_1invalid__format" ],
      [ "unexpected_page", "classpstsdk_1_1unexpected__page.html", "classpstsdk_1_1unexpected__page" ],
      [ "unexpected_block", "classpstsdk_1_1unexpected__block.html", "classpstsdk_1_1unexpected__block" ],
      [ "crc_fail", "classpstsdk_1_1crc__fail.html", "classpstsdk_1_1crc__fail" ],
      [ "sig_mismatch", "classpstsdk_1_1sig__mismatch.html", "classpstsdk_1_1sig__mismatch" ],
      [ "key_not_found", "classpstsdk_1_1key__not__found.html", "classpstsdk_1_1key__not__found" ],
      [ "alias_tag", "structpstsdk_1_1alias__tag.html", null ],
      [ "guid", "structpstsdk_1_1guid.html", "structpstsdk_1_1guid" ],
      [ "file", "classpstsdk_1_1file.html", "classpstsdk_1_1file" ]
    ] ]
];