/*
 * MAPI property tag declarations
 *
 * Copyright 2004 Jon Griffiths
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#ifndef MAPITAGS_H
#define MAPITAGS_H

// #define FIsTransmittable(t) (PROP_ID(t) < 0x0E00 || PROP_ID(t) >= 0x8000 || \
//  (PROP_ID(t) >= 0x1000 && PROP_ID(t) < 0x6000) || \
//  (PROP_ID(t) >= 0x6800 && PROP_ID(t) < 0x7C00))

#define PR_ACKNOWLEDGEMENT_MODE 0x01 // PT_I4
#define PR_ALTERNATE_RECIPIENT_ALLOWED 0x02 // PT_BOOLEAN
#define PR_AUTHORIZING_USERS 0x03 // PT_BINARY
/* Comment on an automatically forwarded message */
#define PR_AUTO_FORWARD_COMMENT_W 0x04 // PT_UNICODE
#define PR_AUTO_FORWARD_COMMENT_A 0x04 // PT_STRING8
/* Whether a message has been automatically forwarded */
#define PR_AUTO_FORWARDED 0x05 // PT_BOOLEAN
#define PR_CONTENT_CONFIDENTIALITY_ALGORITHM_ID 0x06 // PT_BINARY
#define PR_CONTENT_CORRELATOR 0x07 // PT_BINARY
#define PR_CONTENT_IDENTIFIER_W 0x08 // PT_UNICODE
#define PR_CONTENT_IDENTIFIER_A 0x08 // PT_STRING8
/* MIME content length */
#define PR_CONTENT_LENGTH 0x09 // PT_I4
#define PR_CONTENT_RETURN_REQUESTED 0x0A // PT_BOOLEAN
#define PR_CONVERSATION_KEY 0x0B // PT_BINARY
#define PR_CONVERSION_EITS 0x0C // PT_BINARY
#define PR_CONVERSION_WITH_LOSS_PROHIBITED 0x0D // PT_BOOLEAN
#define PR_CONVERTED_EITS 0x0E // PT_BINARY
/* Time to deliver for delayed delivery messages */
#define PR_DEFERRED_DELIVERY_TIME 0x0F // PT_SYSTIME
#define PR_DELIVER_TIME 0x10 // PT_SYSTIME
/* Reason a message was discarded */
#define PR_DISCARD_REASON 0x11 // PT_I4
#define PR_DISCLOSURE_OF_RECIPIENTS 0x12 // PT_BOOLEAN
#define PR_DL_EXPANSION_HISTORY 0x13 // PT_BINARY
#define PR_DL_EXPANSION_PROHIBITED 0x14 // PT_BOOLEAN
#define PR_EXPIRY_TIME 0x15 // PT_SYSTIME
#define PR_IMPLICIT_CONVERSION_PROHIBITED 0x16 // PT_BOOLEAN
/* Message importance */
#define PR_IMPORTANCE 0x17 // PT_I4
#define PR_IPM_ID 0x18 // PT_BINARY
#define PR_LATEST_DELIVERY_TIME 0x19 // PT_SYSTIME
#define PR_MESSAGE_CLASS_W 0x1A // PT_UNICODE
#define PR_MESSAGE_CLASS_A 0x1A // PT_STRING8

#define PR_MESSAGE_DELIVERY_ID 0x1B // PT_BINARY
#define PR_MESSAGE_SECURITY_LABEL 0x1E // PT_BINARY
#define PR_OBSOLETED_IPMS 0x1F // PT_BINARY
/* Person a message was originally for */
#define PR_ORIGINALLY_INTENDED_RECIPIENT_NAME 0x20 // PT_BINARY
#define PR_ORIGINAL_EITS 0x21 // PT_BINARY
#define PR_ORIGINATOR_CERTIFICATE 0x22 // PT_BINARY
#define PR_ORIGINATOR_DELIVERY_REPORT_REQUESTED 0x23 // PT_BOOLEAN
/* Address of the message sender */
#define PR_ORIGINATOR_RETURN_ADDRESS 0x24 // PT_BINARY
#define PR_PARENT_KEY 0x25 // PT_BINARY
#define PR_PRIORITY 0x26 // PT_I4
#define PR_ORIGIN_CHECK 0x27 // PT_BINARY
#define PR_PROOF_OF_SUBMISSION_REQUESTED 0x28 // PT_BOOLEAN
/* Whether a read receipt is desired */
#define PR_READ_RECEIPT_REQUESTED 0x29 // PT_BOOLEAN
/* Time a message was received */
#define PR_RECEIPT_TIME 0x2A // PT_SYSTIME
#define PR_RECIPIENT_REASSIGNMENT_PROHIBITED 0x2B // PT_BOOLEAN
#define PR_REDIRECTION_HISTORY 0x2C // PT_BINARY
#define PR_RELATED_IPMS 0x2D // PT_BINARY
/* Sensitivity of the original message */
#define PR_ORIGINAL_SENSITIVITY 0x2E // PT_I4
#define PR_LANGUAGES_W 0x2F // PT_UNICODE
#define PR_LANGUAGES_A 0x2F // PT_STRING8

#define PR_REPLY_TIME 0x30 // PT_SYSTIME
#define PR_REPORT_TAG 0x31 // PT_BINARY
#define PR_REPORT_TIME 0x32 // PT_SYSTIME
#define PR_RETURNED_IPM 0x33 // PT_BOOLEAN
#define PR_SECURITY 0x34 // PT_I4
#define PR_INCOMPLETE_COPY 0x35 // PT_BOOLEAN
#define PR_SENSITIVITY 0x36 // PT_I4
/* The message subject */
#define PR_SUBJECT_W 0x37 // PT_UNICODE
#define PR_SUBJECT_A 0x37 // PT_STRING8

#define PR_SUBJECT_IPM 0x38 // PT_BINARY
#define PR_CLIENT_SUBMIT_TIME 0x39 // PT_SYSTIME
#define PR_REPORT_NAME_W 0x3A // PT_UNICODE
#define PR_REPORT_NAME_A 0x3A // PT_STRING8

#define PR_SENT_REPRESENTING_SEARCH_KEY 0x3B // PT_BINARY
#define PR_X400_CONTENT_TYPE 0x3C // PT_BINARY
#define PR_SUBJECT_PREFIX_W 0x3D // PT_UNICODE
#define PR_SUBJECT_PREFIX_A 0x3D // PT_STRING8

#define PR_NON_RECEIPT_REASON 0x3E // PT_I4
#define PR_RECEIVED_BY_ENTRYID 0x3F // PT_BINARY
/* Received by: entry */
#define PR_RECEIVED_BY_NAME_W 0x40 // PT_UNICODE
#define PR_RECEIVED_BY_NAME_A 0x40 // PT_STRING8

#define PR_SENT_REPRESENTING_ENTRYID 0x41 // PT_BINARY
#define PR_SENT_REPRESENTING_NAME_W 0x42 // PT_UNICODE
#define PR_SENT_REPRESENTING_NAME_A 0x42 // PT_STRING8

#define PR_RCVD_REPRESENTING_ENTRYID 0x43 // PT_BINARY
#define PR_RCVD_REPRESENTING_NAME_W 0x44 // PT_UNICODE
#define PR_RCVD_REPRESENTING_NAME_A 0x44 // PT_STRING8

#define PR_REPORT_ENTRYID 0x45 // PT_BINARY
#define PR_READ_RECEIPT_ENTRYID 0x46 // PT_BINARY
#define PR_MESSAGE_SUBMISSION_ID 0x47 // PT_BINARY
#define PR_PROVIDER_SUBMIT_TIME 0x48 // PT_SYSTIME
/* Subject of the original message */
#define PR_ORIGINAL_SUBJECT_W 0x49 // PT_UNICODE
#define PR_ORIGINAL_SUBJECT_A 0x49 // PT_STRING8

#define PR_DISC_VAL 0x4A // PT_BOOLEAN
#define PR_ORIG_MESSAGE_CLASS_W 0x4B // PT_UNICODE
#define PR_ORIG_MESSAGE_CLASS_A 0x4B // PT_STRING8

#define PR_ORIGINAL_AUTHOR_ENTRYID 0x4C // PT_BINARY
/* Author of the original message */
#define PR_ORIGINAL_AUTHOR_NAME_W 0x4D // PT_UNICODE
#define PR_ORIGINAL_AUTHOR_NAME_A 0x4D // PT_STRING8

/* Time the original message was submitted */
#define PR_ORIGINAL_SUBMIT_TIME 0x4E // PT_SYSTIME
#define PR_REPLY_RECIPIENT_ENTRIES 0x4F // PT_BINARY
#define PR_REPLY_RECIPIENT_NAMES_W 0x50 // PT_UNICODE
#define PR_REPLY_RECIPIENT_NAMES_A 0x50 // PT_STRING8

#define PR_RECEIVED_BY_SEARCH_KEY 0x51 // PT_BINARY
#define PR_RCVD_REPRESENTING_SEARCH_KEY 0x52 // PT_BINARY
#define PR_READ_RECEIPT_SEARCH_KEY 0x53 // PT_BINARY
#define PR_REPORT_SEARCH_KEY 0x54 // PT_BINARY
#define PR_ORIGINAL_DELIVERY_TIME 0x55 // PT_SYSTIME
#define PR_ORIGINAL_AUTHOR_SEARCH_KEY 0x56 // PT_BINARY
#define PR_MESSAGE_TO_ME 0x57 // PT_BOOLEAN
#define PR_MESSAGE_CC_ME 0x58 // PT_BOOLEAN
#define PR_MESSAGE_RECIP_ME 0x59 // PT_BOOLEAN
/* Sender of the original message */
#define PR_ORIGINAL_SENDER_NAME_W 0x5A // PT_UNICODE
#define PR_ORIGINAL_SENDER_NAME_A 0x5A // PT_STRING8

#define PR_ORIGINAL_SENDER_ENTRYID 0x5B // PT_BINARY
#define PR_ORIGINAL_SENDER_SEARCH_KEY 0x5C // PT_BINARY
#define PR_ORIGINAL_SENT_REPRESENTING_NAME_W 0x5D // PT_UNICODE
#define PR_ORIGINAL_SENT_REPRESENTING_NAME_A 0x5D // PT_STRING8

#define PR_ORIGINAL_SENT_REPRESENTING_ENTRYID 0x5E // PT_BINARY
#define PR_ORIGINAL_SENT_REPRESENTING_SEARCH_KEY 0x5F // PT_BINARY
#define PR_START_DATE 0x60 // PT_SYSTIME
#define PR_END_DATE 0x61 // PT_SYSTIME
#define PR_OWNER_APPT_ID 0x62 // PT_I4
/* Whether a response to the message is desired */
#define PR_RESPONSE_REQUESTED 0x63 // PT_BOOLEAN
#define PR_SENT_REPRESENTING_ADDRTYPE_W 0x64 // PT_UNICODE
#define PR_SENT_REPRESENTING_ADDRTYPE_A 0x64 // PT_STRING8

#define PR_SENT_REPRESENTING_EMAIL_ADDRESS_W 0x65 // PT_UNICODE
#define PR_SENT_REPRESENTING_EMAIL_ADDRESS_A 0x65 // PT_STRING8

#define PR_ORIGINAL_SENDER_ADDRTYPE_W 0x66 // PT_UNICODE
#define PR_ORIGINAL_SENDER_ADDRTYPE_A 0x66 // PT_STRING8

/* Email of the original message sender */
#define PR_ORIGINAL_SENDER_EMAIL_ADDRESS_W 0x67 // PT_UNICODE
#define PR_ORIGINAL_SENDER_EMAIL_ADDRESS_A 0x67 // PT_STRING8

#define PR_ORIGINAL_SENT_REPRESENTING_ADDRTYPE_W 0x68 // PT_UNICODE
#define PR_ORIGINAL_SENT_REPRESENTING_ADDRTYPE_A 0x68 // PT_STRING8

#define PR_ORIGINAL_SENT_REPRESENTING_EMAIL_ADDRESS_W 0x69 // PT_UNICODE
#define PR_ORIGINAL_SENT_REPRESENTING_EMAIL_ADDRESS_A 0x69 // PT_STRING8

#define PR_CONVERSATION_TOPIC_W 0x70 // PT_UNICODE
#define PR_CONVERSATION_TOPIC_A 0x70 // PT_STRING8

#define PR_CONVERSATION_INDEX 0x71 // PT_BINARY
#define PR_ORIGINAL_DISPLAY_BCC_W 0x72 // PT_UNICODE
#define PR_ORIGINAL_DISPLAY_BCC_A 0x72 // PT_STRING8

#define PR_ORIGINAL_DISPLAY_CC_W 0x73 // PT_UNICODE
#define PR_ORIGINAL_DISPLAY_CC_A 0x73 // PT_STRING8

#define PR_ORIGINAL_DISPLAY_TO_W 0x74 // PT_UNICODE
#define PR_ORIGINAL_DISPLAY_TO_A 0x74 // PT_STRING8

#define PR_RECEIVED_BY_ADDRTYPE_W 0x75 // PT_UNICODE
#define PR_RECEIVED_BY_ADDRTYPE_A 0x75 // PT_STRING8

#define PR_RECEIVED_BY_EMAIL_ADDRESS_W 0x76 // PT_UNICODE
#define PR_RECEIVED_BY_EMAIL_ADDRESS_A 0x76 // PT_STRING8

#define PR_RCVD_REPRESENTING_ADDRTYPE_W 0x77 // PT_UNICODE
#define PR_RCVD_REPRESENTING_ADDRTYPE_A 0x77 // PT_STRING8

#define PR_RCVD_REPRESENTING_EMAIL_ADDRESS_W 0x78 // PT_UNICODE
#define PR_RCVD_REPRESENTING_EMAIL_ADDRESS_A 0x78 // PT_STRING8

#define PR_ORIGINAL_AUTHOR_ADDRTYPE_W 0x79 // PT_UNICODE
#define PR_ORIGINAL_AUTHOR_ADDRTYPE_A 0x79 // PT_STRING8

#define PR_ORIGINAL_AUTHOR_EMAIL_ADDRESS_W 0x7A // PT_UNICODE
#define PR_ORIGINAL_AUTHOR_EMAIL_ADDRESS_A 0x7A // PT_STRING8

#define PR_ORIGINALLY_INTENDED_RECIP_ADDRTYPE_W 0x7B // PT_UNICODE
#define PR_ORIGINALLY_INTENDED_RECIP_ADDRTYPE_A 0x7B // PT_STRING8

#define PR_ORIGINALLY_INTENDED_RECIP_EMAIL_ADDRESS_W 0x7C // PT_UNICODE
#define PR_ORIGINALLY_INTENDED_RECIP_EMAIL_ADDRESS_A 0x7C // PT_STRING8

#define PR_TRANSPORT_MESSAGE_HEADERS_W 0x7D // PT_UNICODE
#define PR_TRANSPORT_MESSAGE_HEADERS_A 0x7D // PT_STRING8

#define PR_DELEGATION 0x7E // PT_BINARY
#define PR_TNEF_CORRELATION_KEY 0x7F // PT_BINARY
#define PR_BODY_W 0x1000 // PT_UNICODE
#define PR_BODY_A 0x1000 // PT_STRING8
#define PR_HTML 0x1013

#define PR_REPORT_TEXT_W 0x1001 // PT_UNICODE
#define PR_REPORT_TEXT_A 0x1001 // PT_STRING8

#define PR_ORIGINATOR_AND_DL_EXPANSION_HISTORY 0x1002 // PT_BINARY
#define PR_REPORTING_DL_NAME 0x1003 // PT_BINARY
#define PR_REPORTING_MTA_CERTIFICATE 0x1004 // PT_BINARY
#define PR_RTF_SYNC_BODY_CRC 0x1006 // PT_I4
#define PR_RTF_SYNC_BODY_COUNT 0x1007 // PT_I4
#define PR_RTF_SYNC_BODY_TAG_W 0x1008 // PT_UNICODE
#define PR_RTF_SYNC_BODY_TAG_A 0x1008 // PT_STRING8

#define PR_RTF_COMPRESSED 0x1009 // PT_BINARY
#define PR_RTF_SYNC_PREFIX_COUNT 0x1010 // PT_I4
#define PR_RTF_SYNC_TRAILING_COUNT 0x1011 // PT_I4
#define PR_ORIGINALLY_INTENDED_RECIP_ENTRYID 0x1012 // PT_BINARY
#define PR_INTERNET_MESSAGE_ID 0x1035
#define PR_CONTENT_INTEGRITY_CHECK 0x0C00 // PT_BINARY
#define PR_EXPLICIT_CONVERSION 0x0C01 // PT_I4
#define PR_IPM_RETURN_REQUESTED 0x0C02 // PT_BOOLEAN
#define PR_MESSAGE_TOKEN 0x0C03 // PT_BINARY
#define PR_NDR_REASON_CODE 0x0C04 // PT_I4
#define PR_NDR_DIAG_CODE 0x0C05 // PT_I4
#define PR_NON_RECEIPT_NOTIFICATION_REQUESTED 0x0C06 // PT_BOOLEAN
#define PR_DELIVERY_POINT 0x0C07 // PT_I4
#define PR_ORIGINATOR_NON_DELIVERY_REPORT_REQUESTED 0x0C08 // PT_BOOLEAN
#define PR_ORIGINATOR_REQUESTED_ALTERNATE_RECIPIENT 0x0C09 // PT_BINARY
#define PR_PHYSICAL_DELIVERY_BUREAU_FAX_DELIVERY 0x0C0A // PT_BOOLEAN
#define PR_PHYSICAL_DELIVERY_MODE 0x0C0B // PT_I4
#define PR_PHYSICAL_DELIVERY_REPORT_REQUEST 0x0C0C // PT_I4
#define PR_PHYSICAL_FORWARDING_ADDRESS 0x0C0D // PT_BINARY
#define PR_PHYSICAL_FORWARDING_ADDRESS_REQUESTED 0x0C0E // PT_BOOLEAN
#define PR_PHYSICAL_FORWARDING_PROHIBITED 0x0C0F // PT_BOOLEAN
#define PR_PHYSICAL_RENDITION_ATTRIBUTES 0x0C10 // PT_BINARY
#define PR_PROOF_OF_DELIVERY 0x0C11 // PT_BINARY
#define PR_PROOF_OF_DELIVERY_REQUESTED 0x0C12 // PT_BOOLEAN
#define PR_RECIPIENT_CERTIFICATE 0x0C13 // PT_BINARY
#define PR_RECIPIENT_NUMBER_FOR_ADVICE_W 0x0C14 // PT_UNICODE
#define PR_RECIPIENT_NUMBER_FOR_ADVICE_A 0x0C14 // PT_STRING8

#define PR_RECIPIENT_TYPE 0x0C15 // PT_I4
#define PR_REGISTERED_MAIL_TYPE 0x0C16 // PT_I4
#define PR_REPLY_REQUESTED 0x0C17 // PT_BOOLEAN
#define PR_REQUESTED_DELIVERY_METHOD 0x0C18 // PT_I4
#define PR_SENDER_ENTRYID 0x0C19 // PT_BINARY
#define PR_SENDER_NAME_W 0x0C1A // PT_UNICODE
#define PR_SENDER_NAME_A 0x0C1A // PT_STRING8

#define PR_SUPPLEMENTARY_INFO_W 0x0C1B // PT_UNICODE
#define PR_SUPPLEMENTARY_INFO_A 0x0C1B // PT_STRING8

#define PR_TYPE_OF_MTS_USER 0x0C1C // PT_I4
#define PR_SENDER_SEARCH_KEY 0x0C1D // PT_BINARY
#define PR_SENDER_ADDRTYPE_W 0x0C1E // PT_UNICODE
#define PR_SENDER_ADDRTYPE_A 0x0C1E // PT_STRING8

#define PR_SENDER_EMAIL_ADDRESS_W 0x0C1F // PT_UNICODE
#define PR_SENDER_EMAIL_ADDRESS_A 0x0C1F // PT_STRING8

#define PR_CURRENT_VERSION 0x0E00 // PT_I8
#define PR_DELETE_AFTER_SUBMIT 0x0E01 // PT_BOOLEAN
#define PR_DISPLAY_BCC_W 0x0E02 // PT_UNICODE
#define PR_DISPLAY_BCC_A 0x0E02 // PT_STRING8

#define PR_DISPLAY_CC_W 0x0E03 // PT_UNICODE
#define PR_DISPLAY_CC_A 0x0E03 // PT_STRING8

#define PR_DISPLAY_TO_W 0x0E04 // PT_UNICODE
#define PR_DISPLAY_TO_A 0x0E04 // PT_STRING8

#define PR_PARENT_DISPLAY_W 0x0E05 // PT_UNICODE
#define PR_PARENT_DISPLAY_A 0x0E05 // PT_STRING8

#define PR_MESSAGE_DELIVERY_TIME 0x0E06 // PT_SYSTIME
#define PR_MESSAGE_FLAGS 0x0E07 // PT_I4
#define PR_MESSAGE_SIZE 0x0E08 // PT_I4
#define PR_PARENT_ENTRYID 0x0E09 // PT_BINARY
#define PR_SENTMAIL_ENTRYID 0x0E0A // PT_BINARY
#define PR_CORRELATE 0x0E0C // PT_BOOLEAN
#define PR_CORRELATE_MTSID 0x0E0D // PT_BINARY
#define PR_DISCRETE_VALUES 0x0E0E // PT_BOOLEAN
#define PR_RESPONSIBILITY 0x0E0F // PT_BOOLEAN
#define PR_SPOOLER_STATUS 0x0E10 // PT_I4
#define PR_TRANSPORT_STATUS 0x0E11 // PT_I4
#define PR_MESSAGE_RECIPIENTS 0x0E12 // PT_OBJECT
#define PR_MESSAGE_ATTACHMENTS 0x0E13 // PT_OBJECT
#define PR_SUBMIT_FLAGS 0x0E14 // PT_I4
#define PR_RECIPIENT_STATUS 0x0E15 // PT_I4
#define PR_TRANSPORT_KEY 0x0E16 // PT_I4
#define PR_MSG_STATUS 0x0E17 // PT_I4
#define PR_MESSAGE_DOWNLOAD_TIME 0x0E18 // PT_I4
#define PR_CREATION_VERSION 0x0E19 // PT_I8
#define PR_MODIFY_VERSION 0x0E1A // PT_I8
#define PR_HASATTACH 0x0E1B // PT_BOOLEAN
#define PR_BODY_CRC  0x0E1C // PT_I4
#define PR_NORMALIZED_SUBJECT_W 0x0E1D // PT_UNICODE
#define PR_NORMALIZED_SUBJECT_A 0x0E1D // PT_STRING8

#define PR_RTF_IN_SYNC 0x0E1F // PT_BOOLEAN
#define PR_ATTACH_SIZE 0x0E20 // PT_I4
#define PR_ATTACH_NUM 0x0E21 // PT_I4
#define PR_PREPROCESS 0x0E22 // PT_BOOLEAN
#define PR_ORIGINATING_MTA_CERTIFICATE 0x0E25 // PT_BINARY
#define PR_PROOF_OF_SUBMISSION 0x0E26 // PT_BINARY
/* A unique identifier for editing the properties of a MAPI object */
#define PR_ENTRYID 0x0FFF // PT_BINARY
/* The type of an object */
#define PR_OBJECT_TYPE 0x0FFE // PT_I4
#define PR_ICON 0x0FFD // PT_BINARY
#define PR_MINI_ICON 0x0FFC // PT_BINARY
#define PR_STORE_ENTRYID 0x0FFB // PT_BINARY
#define PR_STORE_RECORD_KEY 0x0FFA // PT_BINARY
/* Binary identifier for an individual object */
#define PR_RECORD_KEY 0x0FF9 // PT_BINARY
#define PR_MAPPING_SIGNATURE 0x0FF8 // PT_BINARY
#define PR_ACCESS_LEVEL 0x0FF7 // PT_I4
/* The primary key of a column in a table */
#define PR_INSTANCE_KEY 0x0FF6 // PT_BINARY
#define PR_ROW_TYPE 0x0FF5 // PT_I4
#define PR_ACCESS 0x0FF4 // PT_I4
#define PR_ROWID 0x3000 // PT_I4
/* The name to display for a given MAPI object */
#define PR_DISPLAY_NAME_W 0x3001 // PT_UNICODE
#define PR_DISPLAY_NAME_A 0x3001 // PT_STRING8

#define PR_ADDRTYPE_W 0x3002 // PT_UNICODE
#define PR_ADDRTYPE_A 0x3002 // PT_STRING8

/* An email address */
#define PR_EMAIL_ADDRESS_W 0x3003 // PT_UNICODE
#define PR_EMAIL_ADDRESS_A 0x3003 // PT_STRING8

/* A comment field */
#define PR_COMMENT_W 0x3004 // PT_UNICODE
#define PR_COMMENT_A 0x3004 // PT_STRING8

#define PR_DEPTH 0x3005 // PT_I4
/* Provider-defined display name for a service provider */
#define PR_PROVIDER_DISPLAY_W 0x3006 // PT_UNICODE
#define PR_PROVIDER_DISPLAY_A 0x3006 // PT_STRING8

/* The time an object was created */
#define PR_CREATION_TIME 0x3007 // PT_SYSTIME
/* The time an object was last modified */
#define PR_LAST_MODIFICATION_TIME 0x3008 // PT_SYSTIME
/* Flags describing a service provider, message service, or status object */
#define PR_RESOURCE_FLAGS 0x3009 // PT_I4
/* The name of a provider dll, minus any "32" suffix and ".dll" */
#define PR_PROVIDER_DLL_NAME_W 0x300A // PT_UNICODE
#define PR_PROVIDER_DLL_NAME_A 0x300A // PT_STRING8

#define PR_SEARCH_KEY 0x300B // PT_BINARY
#define PR_PROVIDER_UID 0x300C // PT_BINARY
#define PR_PROVIDER_ORDINAL 0x300D // PT_I4
#define PR_FORM_VERSION_W 0x3301 // PT_UNICODE
#define PR_FORM_VERSION_A 0x3301 // PT_STRING8

#define PR_FORM_CLSID 0x3302 // PT_CLSID
#define PR_FORM_CONTACT_NAME_W 0x3303 // PT_UNICODE
#define PR_FORM_CONTACT_NAME_A 0x3303 // PT_STRING8

#define PR_FORM_CATEGORY_W 0x3304 // PT_UNICODE
#define PR_FORM_CATEGORY_A 0x3304 // PT_STRING8

#define PR_FORM_CATEGORY_SUB_W 0x3305 // PT_UNICODE
#define PR_FORM_CATEGORY_SUB_A 0x3305 // PT_STRING8

#define PR_FORM_HOST_MAP 0x3306 // PT_MV_LONG
#define PR_FORM_HIDDEN 0x3307 // PT_BOOLEAN
#define PR_FORM_DESIGNER_NAME_W 0x3308 // PT_UNICODE
#define PR_FORM_DESIGNER_NAME_A 0x3308 // PT_STRING8

#define PR_FORM_DESIGNER_GUID 0x3309 // PT_CLSID
#define PR_FORM_MESSAGE_BEHAVIOR 0x330A // PT_I4
/* Is this row the default message store? */
#define PR_DEFAULT_STORE 0x3400 // PT_BOOLEAN
#define PR_STORE_SUPPORT_MASK 0x340D // PT_I4
#define PR_STORE_STATE 0x340E // PT_I4
#define PR_IPM_SUBTREE_SEARCH_KEY 0x3410 // PT_BINARY
#define PR_IPM_OUTBOX_SEARCH_KEY 0x3411 // PT_BINARY
#define PR_IPM_WASTEBASKET_SEARCH_KEY 0x3412 // PT_BINARY
#define PR_IPM_SENTMAIL_SEARCH_KEY 0x3413 // PT_BINARY
/* Provider-defined message store type */
#define PR_MDB_PROVIDER 0x3414 // PT_BINARY
#define PR_RECEIVE_FOLDER_SETTINGS 0x3415 // PT_OBJECT
#define PR_VALID_FOLDER_MASK 0x35DF // PT_I4
#define PR_IPM_SUBTREE_ENTRYID 0x35E0 // PT_BINARY
#define PR_IPM_OUTBOX_ENTRYID 0x35E2 // PT_BINARY
#define PR_IPM_WASTEBASKET_ENTRYID 0x35E3 // PT_BINARY
#define PR_IPM_SENTMAIL_ENTRYID 0x35E4 // PT_BINARY
#define PR_VIEWS_ENTRYID 0x35E5 // PT_BINARY
#define PR_COMMON_VIEWS_ENTRYID 0x35E6 // PT_BINARY
#define PR_FINDER_ENTRYID 0x35E7 // PT_BINARY
#define PR_CONTAINER_FLAGS 0x3600 // PT_I4
#define PR_FOLDER_TYPE 0x3601 // PT_I4
#define PR_CONTENT_COUNT 0x3602 // PT_I4
#define PR_CONTENT_UNREAD 0x3603 // PT_I4
#define PR_CREATE_TEMPLATES 0x3604 // PT_OBJECT
#define PR_DETAILS_TABLE 0x3605 // PT_OBJECT
#define PR_SEARCH 0x3607 // PT_OBJECT
#define PR_SELECTABLE 0x3609 // PT_BOOLEAN
#define PR_SUBFOLDERS 0x360A // PT_BOOLEAN
#define PR_STATUS 0x360B // PT_I4
#define PR_ANR_W 0x360C // PT_UNICODE
#define PR_ANR_A 0x360C // PT_STRING8

#define PR_CONTENTS_SORT_ORDER 0x360D // PT_MV_LONG
#define PR_CONTAINER_HIERARCHY 0x360E // PT_OBJECT
#define PR_CONTAINER_CONTENTS 0x360F // PT_OBJECT
#define PR_FOLDER_ASSOCIATED_CONTENTS 0x3610 // PT_OBJECT
#define PR_DEF_CREATE_DL 0x3611 // PT_BINARY
#define PR_DEF_CREATE_MAILUSER 0x3612 // PT_BINARY
#define PR_CONTAINER_CLASS_W 0x3613 // PT_UNICODE
#define PR_CONTAINER_CLASS_A 0x3613 // PT_STRING8

#define PR_CONTAINER_MODIFY_VERSION 0x3614 // PT_I8
#define PR_AB_PROVIDER_ID 0x3615 // PT_BINARY
#define PR_DEFAULT_VIEW_ENTRYID 0x3616 // PT_BINARY
#define PR_ASSOC_CONTENT_COUNT 0x3617 // PT_I4
#define PR_IPM_DRAFTS_ENTRYID 0x36D7 // PT_BINARY
#define PR_ATTACHMENT_X400_PARAMETERS 0x3700 // PT_BINARY
#define PR_ATTACH_DATA_OBJ 0x3701 // PT_OBJECT
#define PR_ATTACH_DATA_BIN 0x3701 // PT_BINARY
#define PR_ATTACH_ENCODING 0x3702 // PT_BINARY
#define PR_ATTACH_EXTENSION_W 0x3703 // PT_UNICODE
#define PR_ATTACH_EXTENSION_A 0x3703 // PT_STRING8

#define PR_ATTACH_FILENAME_W 0x3704 // PT_UNICODE
#define PR_ATTACH_FILENAME_A 0x3704 // PT_STRING8

#define PR_ATTACH_METHOD 0x3705 // PT_I4
#define PR_ATTACH_LONG_FILENAME_W 0x3707 // PT_UNICODE
#define PR_ATTACH_LONG_FILENAME_A 0x3707 // PT_STRING8

#define PR_ATTACH_PATHNAME_W 0x3708 // PT_UNICODE
#define PR_ATTACH_PATHNAME_A 0x3708 // PT_STRING8

#define PR_ATTACH_RENDERING  0x3709 // PT_BINARY
#define PR_ATTACH_TAG 0x370A // PT_BINARY
#define PR_RENDERING_POSITION 0x370B // PT_I4
#define PR_ATTACH_TRANSPORT_NAME_W 0x370C // PT_UNICODE
#define PR_ATTACH_TRANSPORT_NAME_A 0x370C // PT_STRING8

#define PR_ATTACH_LONG_PATHNAME_W 0x370D // PT_UNICODE
#define PR_ATTACH_LONG_PATHNAME_A 0x370D // PT_STRING8

#define PR_ATTACH_MIME_TAG_W 0x370E // PT_UNICODE
#define PR_ATTACH_MIME_TAG_A 0x370E // PT_STRING8

#define PR_ATTACH_ADDITIONAL_INFO 0x370F // PT_BINARY
#define PR_ATTACH_CONTENT_ID 0x3712 // PT_STRING8
#define PR_DISPLAY_TYPE 0x3900 // PT_I4
#define PR_TEMPLATEID 0x3902 // PT_BINARY
#define PR_PRIMARY_CAPABILITY 0x3904 // PT_BINARY
#define PR_7BIT_DISPLAY_NAME 0x39FF // PT_STRING8
#define PR_ACCOUNT_W 0x3A00 // PT_UNICODE
#define PR_ACCOUNT_A 0x3A00 // PT_STRING8

#define PR_ALTERNATE_RECIPIENT 0x3A01 // PT_BINARY
#define PR_CALLBACK_TELEPHONE_NUMBER_W 0x3A02 // PT_UNICODE
#define PR_CALLBACK_TELEPHONE_NUMBER_A 0x3A02 // PT_STRING8

#define PR_CONVERSION_PROHIBITED 0x3A03 // PT_BOOLEAN
#define PR_DISCLOSE_RECIPIENTS 0x3A04 // PT_BOOLEAN
#define PR_GENERATION_W 0x3A05 // PT_UNICODE
#define PR_GENERATION_A 0x3A05 // PT_STRING8

#define PR_GIVEN_NAME_W 0x3A06 // PT_UNICODE
#define PR_GIVEN_NAME_A 0x3A06 // PT_STRING8

#define PR_GOVERNMENT_ID_NUMBER_W 0x3A07 // PT_UNICODE
#define PR_GOVERNMENT_ID_NUMBER_A 0x3A07 // PT_STRING8

#define PR_BUSINESS_TELEPHONE_NUMBER_W 0x3A08 // PT_UNICODE
#define PR_BUSINESS_TELEPHONE_NUMBER_A 0x3A08 // PT_STRING8

#define PR_OFFICE_TELEPHONE_NUMBER_W PR_BUSINESS_TELEPHONE_NUMBER_W
#define PR_OFFICE_TELEPHONE_NUMBER_A PR_BUSINESS_TELEPHONE_NUMBER_A

#define PR_HOME_TELEPHONE_NUMBER_W 0x3A09 // PT_UNICODE
#define PR_HOME_TELEPHONE_NUMBER_A 0x3A09 // PT_STRING8

#define PR_INITIALS_W 0x3A0A // PT_UNICODE
#define PR_INITIALS_A 0x3A0A // PT_STRING8

#define PR_KEYWORD_W 0x3A0B // PT_UNICODE
#define PR_KEYWORD_A 0x3A0B // PT_STRING8

#define PR_LANGUAGE_W 0x3A0C // PT_UNICODE
#define PR_LANGUAGE_A 0x3A0C // PT_STRING8

#define PR_LOCATION_W 0x3A0D // PT_UNICODE
#define PR_LOCATION_A 0x3A0D // PT_STRING8

#define PR_MAIL_PERMISSION 0x3A0E // PT_BOOLEAN
#define PR_MHS_COMMON_NAME_W 0x3A0F // PT_UNICODE
#define PR_MHS_COMMON_NAME_A 0x3A0F // PT_STRING8

#define PR_ORGANIZATIONAL_ID_NUMBER_W 0x3A10 // PT_UNICODE
#define PR_ORGANIZATIONAL_ID_NUMBER_A 0x3A10 // PT_STRING8

#define PR_SURNAME_W 0x3A11 // PT_UNICODE
#define PR_SURNAME_A 0x3A11 // PT_STRING8

#define PR_ORIGINAL_ENTRYID 0x3A12 // PT_BINARY
#define PR_ORIGINAL_DISPLAY_NAME_W 0x3A13 // PT_UNICODE
#define PR_ORIGINAL_DISPLAY_NAME_A 0x3A13 // PT_STRING8

#define PR_ORIGINAL_SEARCH_KEY 0x3A14 // PT_BINARY
#define PR_POSTAL_ADDRESS_W 0x3A15 // PT_UNICODE
#define PR_POSTAL_ADDRESS_A 0x3A15 // PT_STRING8

#define PR_COMPANY_NAME_W 0x3A16 // PT_UNICODE
#define PR_COMPANY_NAME_A 0x3A16 // PT_STRING8

#define PR_TITLE_W 0x3A17 // PT_UNICODE
#define PR_TITLE_A 0x3A17 // PT_STRING8

#define PR_DEPARTMENT_NAME_W 0x3A18 // PT_UNICODE
#define PR_DEPARTMENT_NAME_A 0x3A18 // PT_STRING8

#define PR_OFFICE_LOCATION_W 0x3A19 // PT_UNICODE
#define PR_OFFICE_LOCATION_A 0x3A19 // PT_STRING8

#define PR_PRIMARY_TELEPHONE_NUMBER_W 0x3A1A // PT_UNICODE
#define PR_PRIMARY_TELEPHONE_NUMBER_A 0x3A1A // PT_STRING8

#define PR_BUSINESS2_TELEPHONE_NUMBER_W 0x3A1B // PT_UNICODE
#define PR_BUSINESS2_TELEPHONE_NUMBER_A 0x3A1B // PT_STRING8

#define PR_OFFICE2_TELEPHONE_NUMBER_W PR_BUSINESS2_TELEPHONE_NUMBER_W
#define PR_OFFICE2_TELEPHONE_NUMBER_A PR_BUSINESS2_TELEPHONE_NUMBER_A

#define PR_MOBILE_TELEPHONE_NUMBER_W 0x3A1C // PT_UNICODE
#define PR_MOBILE_TELEPHONE_NUMBER_A 0x3A1C // PT_STRING8

#define PR_CELLULAR_TELEPHONE_NUMBER_W PR_MOBILE_TELEPHONE_NUMBER_W
#define PR_CELLULAR_TELEPHONE_NUMBER_A PR_MOBILE_TELEPHONE_NUMBER_A

#define PR_RADIO_TELEPHONE_NUMBER_W 0x3A1D // PT_UNICODE
#define PR_RADIO_TELEPHONE_NUMBER_A 0x3A1D // PT_STRING8

#define PR_CAR_TELEPHONE_NUMBER_W 0x3A1E // PT_UNICODE
#define PR_CAR_TELEPHONE_NUMBER_A 0x3A1E // PT_STRING8

#define PR_OTHER_TELEPHONE_NUMBER_W 0x3A1F // PT_UNICODE
#define PR_OTHER_TELEPHONE_NUMBER_A 0x3A1F // PT_STRING8

#define PR_TRANSMITABLE_DISPLAY_NAME_W 0x3A20 // PT_UNICODE
#define PR_TRANSMITABLE_DISPLAY_NAME_A 0x3A20 // PT_STRING8

#define PR_PAGER_TELEPHONE_NUMBER_W 0x3A21 // PT_UNICODE
#define PR_PAGER_TELEPHONE_NUMBER_A 0x3A21 // PT_STRING8

#define PR_BEEPER_TELEPHONE_NUMBER_W PR_PAGER_TELEPHONE_NUMBER_W
#define PR_BEEPER_TELEPHONE_NUMBER_A PR_PAGER_TELEPHONE_NUMBER_A

#define PR_USER_CERTIFICATE 0x3A22 // PT_BINARY
#define PR_PRIMARY_FAX_NUMBER_W 0x3A23 // PT_UNICODE
#define PR_PRIMARY_FAX_NUMBER_A 0x3A23 // PT_STRING8

#define PR_BUSINESS_FAX_NUMBER_W 0x3A24 // PT_UNICODE
#define PR_BUSINESS_FAX_NUMBER_A 0x3A24 // PT_STRING8

#define PR_HOME_FAX_NUMBER_W 0x3A25 // PT_UNICODE
#define PR_HOME_FAX_NUMBER_A 0x3A25 // PT_STRING8

#define PR_COUNTRY_W 0x3A26 // PT_UNICODE
#define PR_COUNTRY_A 0x3A26 // PT_STRING8

#define PR_BUSINESS_ADDRESS_COUNTRY_W PR_COUNTRY_W
#define PR_BUSINESS_ADDRESS_COUNTRY_A PR_COUNTRY_A

#define PR_LOCALITY_W 0x3A27 // PT_UNICODE
#define PR_LOCALITY_A 0x3A27 // PT_STRING8

#define PR_BUSINESS_ADDRESS_CITY_W PR_LOCALITY_W
#define PR_BUSINESS_ADDRESS_CITY_A PR_LOCALITY_A

#define PR_STATE_OR_PROVINCE_W 0x3A28 // PT_UNICODE
#define PR_STATE_OR_PROVINCE_A 0x3A28 // PT_STRING8

#define PR_BUSINESS_ADDRESS_STATE_OR_PROVINCE_W PR_STATE_OR_PROVINCE_W
#define PR_BUSINESS_ADDRESS_STATE_OR_PROVINCE_A PR_STATE_OR_PROVINCE_A

#define PR_STREET_ADDRESS_W 0x3A29 // PT_UNICODE
#define PR_STREET_ADDRESS_A 0x3A29 // PT_STRING8

#define PR_BUSINESS_ADDRESS_STREET_W PR_STREET_ADDRESS_W
#define PR_BUSINESS_ADDRESS_STREET_A PR_STREET_ADDRESS_A

#define PR_POSTAL_CODE_W 0x3A2A // PT_UNICODE
#define PR_POSTAL_CODE_A 0x3A2A // PT_STRING8

#define PR_BUSINESS_ADDRESS_POSTAL_CODE_W PR_POSTAL_CODE_W
#define PR_BUSINESS_ADDRESS_POSTAL_CODE_A PR_POSTAL_CODE_A

#define PR_POST_OFFICE_BOX_W 0x3A2B // PT_UNICODE
#define PR_POST_OFFICE_BOX_A 0x3A2B // PT_STRING8

#define PR_BUSINESS_ADDRESS_POST_OFFICE_BOX_W PR_POST_OFFICE_BOX_W
#define PR_BUSINESS_ADDRESS_POST_OFFICE_BOX_A PR_POST_OFFICE_BOX_A

#define PR_TELEX_NUMBER_W 0x3A2C // PT_UNICODE
#define PR_TELEX_NUMBER_A 0x3A2C // PT_STRING8

#define PR_ISDN_NUMBER_W 0x3A2D // PT_UNICODE
#define PR_ISDN_NUMBER_A 0x3A2D // PT_STRING8

#define PR_ASSISTANT_TELEPHONE_NUMBER_W 0x3A2E // PT_UNICODE
#define PR_ASSISTANT_TELEPHONE_NUMBER_A 0x3A2E // PT_STRING8

#define PR_HOME2_TELEPHONE_NUMBER_W 0x3A2F // PT_UNICODE
#define PR_HOME2_TELEPHONE_NUMBER_A 0x3A2F // PT_STRING8

#define PR_ASSISTANT_W 0x3A30 // PT_UNICODE
#define PR_ASSISTANT_A 0x3A30 // PT_STRING8

#define PR_SEND_RICH_INFO 0x3A40 // PT_BOOLEAN
#define PR_WEDDING_ANNIVERSARY 0x3A41 // PT_SYSTIME
#define PR_BIRTHDAY 0x3A42 // PT_SYSTIME
#define PR_HOBBIES_W 0x3A43 // PT_UNICODE
#define PR_HOBBIES_A 0x3A43 // PT_STRING8

#define PR_MIDDLE_NAME_W 0x3A44 // PT_UNICODE
#define PR_MIDDLE_NAME_A 0x3A44 // PT_STRING8

#define PR_DISPLAY_NAME_PREFIX_W 0x3A45 // PT_UNICODE
#define PR_DISPLAY_NAME_PREFIX_A 0x3A45 // PT_STRING8

#define PR_PROFESSION_W 0x3A46 // PT_UNICODE
#define PR_PROFESSION_A 0x3A46 // PT_STRING8

#define PR_PREFERRED_BY_NAME_W 0x3A47 // PT_UNICODE
#define PR_PREFERRED_BY_NAME_A 0x3A47 // PT_STRING8

#define PR_SPOUSE_NAME_W 0x3A48 // PT_UNICODE
#define PR_SPOUSE_NAME_A 0x3A48 // PT_STRING8

#define PR_COMPUTER_NETWORK_NAME_W 0x3A49 // PT_UNICODE
#define PR_COMPUTER_NETWORK_NAME_A 0x3A49 // PT_STRING8

#define PR_CUSTOMER_ID_W 0x3A4A // PT_UNICODE
#define PR_CUSTOMER_ID_A 0x3A4A // PT_STRING8

#define PR_TTYTDD_PHONE_NUMBER_W 0x3A4B // PT_UNICODE
#define PR_TTYTDD_PHONE_NUMBER_A 0x3A4B // PT_STRING8

#define PR_FTP_SITE_W 0x3A4C // PT_UNICODE
#define PR_FTP_SITE_A 0x3A4C // PT_STRING8

#define PR_GENDER 0x3A4D // PT_I2
#define PR_MANAGER_NAME_W 0x3A4E // PT_UNICODE
#define PR_MANAGER_NAME_A 0x3A4E // PT_STRING8

#define PR_NICKNAME_W 0x3A4F // PT_UNICODE
#define PR_NICKNAME_A 0x3A4F // PT_STRING8

#define PR_PERSONAL_HOME_PAGE_W 0x3A50 // PT_UNICODE
#define PR_PERSONAL_HOME_PAGE_A 0x3A50 // PT_STRING8

#define PR_BUSINESS_HOME_PAGE_W 0x3A51 // PT_UNICODE
#define PR_BUSINESS_HOME_PAGE_A 0x3A51 // PT_STRING8

#define PR_CONTACT_VERSION 0x3A52 // PT_CLSID
#define PR_CONTACT_ENTRYIDS 0x3A53 // PT_MV_BINARY
#define PR_CONTACT_ADDRTYPES_W 0x3A54 // PT_MV_UNICODE
#define PR_CONTACT_ADDRTYPES_A 0x3A54 // PT_MV_STRING8

#define PR_CONTACT_DEFAULT_ADDRESS_INDEX 0x3A55 // PT_I4
#define PR_CONTACT_EMAIL_ADDRESSES_W 0x3A56 // PT_MV_UNICODE
#define PR_CONTACT_EMAIL_ADDRESSES_A 0x3A56 // PT_MV_STRING8

#define PR_COMPANY_MAIN_PHONE_NUMBER_W 0x3A57 // PT_UNICODE
#define PR_COMPANY_MAIN_PHONE_NUMBER_A 0x3A57 // PT_STRING8

#define PR_CHILDRENS_NAMES_W 0x3A58 // PT_MV_UNICODE
#define PR_CHILDRENS_NAMES_A 0x3A58 // PT_MV_STRING8

#define PR_HOME_ADDRESS_CITY_W 0x3A59 // PT_UNICODE
#define PR_HOME_ADDRESS_CITY_A 0x3A59 // PT_STRING8

#define PR_HOME_ADDRESS_COUNTRY_W 0x3A5A // PT_UNICODE
#define PR_HOME_ADDRESS_COUNTRY_A 0x3A5A // PT_STRING8

#define PR_HOME_ADDRESS_POSTAL_CODE_W 0x3A5B // PT_UNICODE
#define PR_HOME_ADDRESS_POSTAL_CODE_A 0x3A5B // PT_STRING8

#define PR_HOME_ADDRESS_STATE_OR_PROVINCE_W 0x3A5C // PT_UNICODE
#define PR_HOME_ADDRESS_STATE_OR_PROVINCE_A 0x3A5C // PT_STRING8

#define PR_HOME_ADDRESS_STREET_W 0x3A5D // PT_UNICODE
#define PR_HOME_ADDRESS_STREET_A 0x3A5D // PT_STRING8

#define PR_HOME_ADDRESS_POST_OFFICE_BOX_W 0x3A5E // PT_UNICODE
#define PR_HOME_ADDRESS_POST_OFFICE_BOX_A 0x3A5E // PT_STRING8

#define PR_OTHER_ADDRESS_CITY_W 0x3A5F // PT_UNICODE
#define PR_OTHER_ADDRESS_CITY_A 0x3A5F // PT_STRING8

#define PR_OTHER_ADDRESS_COUNTRY_W 0x3A60 // PT_UNICODE
#define PR_OTHER_ADDRESS_COUNTRY_A 0x3A60 // PT_STRING8

#define PR_OTHER_ADDRESS_POSTAL_CODE_W 0x3A61 // PT_UNICODE
#define PR_OTHER_ADDRESS_POSTAL_CODE_A 0x3A61 // PT_STRING8

#define PR_OTHER_ADDRESS_STATE_OR_PROVINCE_W 0x3A62 // PT_UNICODE
#define PR_OTHER_ADDRESS_STATE_OR_PROVINCE_A 0x3A62 // PT_STRING8

#define PR_OTHER_ADDRESS_STREET_W 0x3A63 // PT_UNICODE
#define PR_OTHER_ADDRESS_STREET_A 0x3A63 // PT_STRING8

#define PR_OTHER_ADDRESS_POST_OFFICE_BOX_W 0x3A64 // PT_UNICODE
#define PR_OTHER_ADDRESS_POST_OFFICE_BOX_A 0x3A64 // PT_STRING8

#define PR_STORE_PROVIDERS 0x3D00 // PT_BINARY
#define PR_AB_PROVIDERS 0x3D01 // PT_BINARY
#define PR_TRANSPORT_PROVIDERS 0x3D02 // PT_BINARY
#define PR_DEFAULT_PROFILE 0x3D04 // PT_BOOLEAN
#define PR_AB_SEARCH_PATH 0x3D05 // PT_MV_BINARY
#define PR_AB_DEFAULT_DIR 0x3D06 // PT_BINARY
#define PR_AB_DEFAULT_PAB 0x3D07 // PT_BINARY
#define PR_FILTERING_HOOKS  0x3D08 // PT_BINARY
#define PR_SERVICE_NAME_W 0x3D09 // PT_UNICODE
#define PR_SERVICE_NAME_A 0x3D09 // PT_STRING8

#define PR_SERVICE_DLL_NAME_W 0x3D0A // PT_UNICODE
#define PR_SERVICE_DLL_NAME_A 0x3D0A // PT_STRING8

#define PR_SERVICE_ENTRY_NAME 0x3D0B // PT_STRING8
#define PR_SERVICE_UID 0x3D0C // PT_BINARY
#define PR_SERVICE_EXTRA_UIDS 0x3D0D // PT_BINARY
#define PR_SERVICES 0x3D0E // PT_BINARY
#define PR_SERVICE_SUPPORT_FILES_W 0x3D0F // PT_MV_UNICODE
#define PR_SERVICE_SUPPORT_FILES_A 0x3D0F // PT_MV_STRING8

#define PR_SERVICE_DELETE_FILES_W 0x3D10 // PT_MV_UNICODE
#define PR_SERVICE_DELETE_FILES_A 0x3D10 // PT_MV_STRING8

#define PR_AB_SEARCH_PATH_UPDATE 0x3D11 // PT_BINARY
#define PR_PROFILE_NAME_A 0x3D12 // PT_STRING8
#define PR_PROFILE_NAME_W 0x3D12 // PT_UNICODE

#define PR_IDENTITY_DISPLAY_W 0x3E00 // PT_UNICODE
#define PR_IDENTITY_DISPLAY_A 0x3E00 // PT_STRING8

#define PR_IDENTITY_ENTRYID 0x3E01 // PT_BINARY
#define PR_RESOURCE_METHODS 0x3E02 // PT_I4
/* Service provider type */
#define PR_RESOURCE_TYPE 0x3E03 // PT_I4
#define PR_STATUS_CODE 0x3E04 // PT_I4
#define PR_IDENTITY_SEARCH_KEY 0x3E05 // PT_BINARY
#define PR_OWN_STORE_ENTRYID 0x3E06 // PT_BINARY
#define PR_RESOURCE_PATH_W 0x3E07 // PT_UNICODE
#define PR_RESOURCE_PATH_A 0x3E07 // PT_STRING8

#define PR_STATUS_STRING_W 0x3E08 // PT_UNICODE
#define PR_STATUS_STRING_A 0x3E08 // PT_STRING8

#define PR_X400_DEFERRED_DELIVERY_CANCEL 0x3E09 // PT_BOOLEAN
#define PR_HEADER_FOLDER_ENTRYID 0x3E0A // PT_BINARY
#define PR_REMOTE_PROGRESS 0x3E0B // PT_I4
#define PR_REMOTE_PROGRESS_TEXT_W 0x3E0C // PT_UNICODE
#define PR_REMOTE_PROGRESS_TEXT_A 0x3E0C // PT_STRING8

#define PR_REMOTE_VALIDATE_OK 0x3E0D // PT_BOOLEAN
#define PR_CONTROL_FLAGS 0x3F00 // PT_I4
#define PR_CONTROL_STRUCTURE 0x3F01 // PT_BINARY
#define PR_CONTROL_TYPE 0x3F02 // PT_I4
#define PR_DELTAX 0x3F03 // PT_I4
#define PR_DELTAY 0x3F04 // PT_I4
#define PR_XPOS 0x3F05 // PT_I4
#define PR_YPOS 0x3F06 // PT_I4
#define PR_CONTROL_ID 0x3F07 // PT_BINARY
#define PR_INITIAL_DETAILS_PANE 0x3F08 // PT_I4

#define PROP_ID_SECURE_MIN 0x67F0
#define PROP_ID_SECURE_MAX 0x67FF

/** MAPI named properties */

/** PSETID_APPOINTMENT */
#define PidLidSendMeetingAsIcal 0x8200 // PT_BOOLEAN
#define PidLidAppointmentSequence 0x8201 // PT_I4
#define PidLidAppointmentSequenceTime 0x8202 // PT_SYSTIME
#define PidLidAppointmentLastSequence 0x8203 // PT_I4
#define PidLidChangeHighlight 0x8204 // PT_I4
#define PidLidBusyStatus 0x8205 // PT_I4
#define PidLidFExceptionalBody 0x8206 // PT_BOOLEAN
#define PidLidAppointmentAuxiliaryFlags 0x8207 // PT_I4
#define PidLidLocation_W 0x8208 // PT_UNICODE
#define PidLidLocation_A 0x8208 // PT_STRING8

#define PidLidMeetingWorkspaceUrl_W 0x8209 // PT_UNICODE
#define PidLidMeetingWorkspaceUrl_A 0x8209 // PT_STRING8

#define PidLidForwardInstance 0x820A // PT_BOOLEAN
#define PidLidLinkedTaskItems 0x820C // PT_MV_BINARY
#define PidLidAppointmentStartWhole 0x820D // PT_SYSTIME
#define PidLidAppointmentEndWhole 0x820E // PT_SYSTIME
#define PidLidAppointmentStartTime 0x820F // PT_SYSTIME
#define PidLidAppointmentEndTime 0x8210 // PT_SYSTIME
#define PidLidAppointmentEndDate 0x8211 // PT_SYSTIME
#define PidLidAppointmentStartDate 0x8212 // PT_SYSTIME
#define PidLidAppointmentDuration 0x8213 // PT_I4
#define PidLidAppointmentColor 0x8214 // PT_I4
#define PidLidAppointmentSubType 0x8215 // PT_BOOLEAN
#define PidLidAppointmentRecur 0x8216 // PT_BINARY
#define PidLidAppointmentStateFlags 0x8217 // PT_I4
#define PidLidResponseStatus 0x8218 // PT_I4
#define PidLidAppointmentReplyTime 0x8220 // PT_SYSTIME
#define PidLidRecurring 0x8223 // PT_BOOLEAN
#define PidLidIntendedBusyStatus 0x8224 // PT_I4
#define PidLidAppointmentUpdateTime 0x8226 // PT_SYSTIME
#define PidLidExceptionReplaceTime 0x8228 // PT_SYSTIME
#define PidLidFInvited 0x8229 // PT_BOOLEAN
#define PidLidFExceptionalAttendees 0x822B // PT_BOOLEAN
#define PidLidOwnerName_W 0x822E // PT_UNICODE
#define PidLidOwnerName_A 0x822E // PT_STRING8

#define PidLidFOthersAppointment 0x822F // PT_BOOLEAN
#define PidLidAppointmentReplyName_W 0x8230 // PT_UNICODE
#define PidLidAppointmentReplyName_A 0x8230 // PT_STRING8

#define PidLidRecurrenceType 0x8231 // PT_I4
#define PidLidRecurrencePattern_W 0x8232 // PT_UNICODE
#define PidLidRecurrencePattern_A 0x8232 // PT_STRING8

#define PidLidTimeZoneStruct 0x8233 // PT_BINARY
#define PidLidTimeZoneDescription_W 0x8234 // PT_UNICODE
#define PidLidTimeZoneDescription_A 0x8234 // PT_STRING8

#define PidLidClipStart 0x8235 // PT_SYSTIME
#define PidLidClipEnd 0x8236 // PT_SYSTIME
#define PidLidOriginalStoreEntryId 0x8237 // PT_BINARY
#define PidLidAllAttendeesString_W 0x8238 // PT_UNICODE
#define PidLidAllAttendeesString_A 0x8238 // PT_STRING8

#define PidLidAutoFillLocation 0x823A // PT_BOOLEAN
#define PidLidToAttendeesString_W 0x823B // PT_UNICODE
#define PidLidToAttendeesString_A 0x823B // PT_STRING8

#define PidLidCcAttendeesString_W 0x823C // PT_UNICODE
#define PidLidCcAttendeesString_A 0x823C // PT_STRING8

#define PidLidConferencingCheck 0x8240 // PT_BOOLEAN
#define PidLidConferencingType 0x8241 // PT_I4
#define PidLidDirectory_W 0x8242 // PT_UNICODE
#define PidLidDirectory_A 0x8242 // PT_STRING8

#define PidLidOrganizerAlias_W 0x8243 // PT_UNICODE
#define PidLidOrganizerAlias_A 0x8243 // PT_STRING8

#define PidLidAutoStartCheck 0x8244 // PT_BOOLEAN
#define PidLidAutoStartWhen 0x8245 // PT_I4
#define PidLidAllowExternalCheck 0x8246 // PT_BOOLEAN
#define PidLidCollaborateDoc_W 0x8247 // PT_UNICODE
#define PidLidCollaborateDoc_A 0x8247 // PT_STRING8

#define PidLidNetShowUrl_W 0x8248 // PT_UNICODE
#define PidLidNetShowUrl_A 0x8248 // PT_STRING8

#define PidLidOnlinePassword_W 0x8249 // PT_UNICODE
#define PidLidOnlinePassword_A 0x8249 // PT_STRING8

#define PidLidAppointmentProposedStartWhole 0x8250 // PT_SYSTIME
#define PidLidAppointmentProposedEndWhole 0x8251 // PT_SYSTIME
#define PidLidAppointmentProposedDuration 0x8256 // PT_I4
#define PidLidAppointmentCounterProposal 0x8257 // PT_BOOLEAN
#define PidLidAppointmentProposalNumber 0x8259 // PT_I4
#define PidLidAppointmentNotAllowPropose 0x825A // PT_BOOLEAN
#define PidLidAppointmentUnsendableRecipients 0x825D // PT_BINARY
#define PidLidAppointmentTimeZoneDefinitionStartDisplay 0x825E // PT_BINARY
#define PidLidAppointmentTimeZoneDefinitionEndDisplay 0x825F // PT_BINARY
#define PidLidAppointmentTimeZoneDefinitionRecur 0x8260 // PT_BINARY
#define PidLidForwardNotificationRecipients 0x8261 // PT_BINARY
#define PidLidInboundICalStream 0x827A // PT_BINARY
#define PidLidSingleBodyIcal 0x827B // PT_BOOLEAN

/** PS_PUBLIC_STRINGS (most use MNID_STRING and have propID 0x0000) */
#define PidLidCategories 0x9000 // PT_MV_STRING8
#define PidNameApplicationName 0x0000 // PT_UNICODE
#define PidNameAuthor 0x0000 // PT_UNICODE
#define PidNameByteCount 0x0000 // PT_I4
#define PidNameCategory 0x0000 // PT_UNICODE
#define PidNameCharacterCount 0x0000 // PT_I4
#define PidNameComments 0x0000 // PT_UNICODE
#define PidNameCompany 0x0000 // PT_UNICODE
#define PidNameCreateDateTimeReadOnly 0x0000 // PT_SYSTIME
#define PidNameRightsManagementLicense 0x0000 // PT_MV_BINARY
#define PidNameEditTime 0x0000 // PT_UNICODE
#define PidNameHiddenCount 0x0000 // PT_I4
#define PidNameKeywords 0x0000 // PT_MV_UNICODE
#define PidNameLastAuthor 0x0000 // PT_UNICODE
#define PidNameLastPrinted 0x0000 // PT_SYSTIME
#define PidNameLastSaveDateTime 0x0000 // PT_SYSTIME
#define PidNameLineCount 0x0000 // PT_I4
#define PidNameManager 0x0000 // PT_UNICODE
#define PidNameMultimediaClipCount 0x0000 // PT_I4
#define PidNameNoteCount 0x0000 // PT_I4
#define PidNamePhishingStamp 0x0000 // PT_I4
#define PidNameSpoofingStamp 0x0000 // PT_I4
#define PidNamePageCount 0x0000 // PT_I4
#define PidNameParagraphCount 0x0000 // PT_I4
#define PidNamePresentationFormat 0x0000 // PT_UNICODE
#define PidNameSecurity 0x0000 // PT_I4
#define PidNameSlideCount 0x0000 // PT_I4
#define PidNameSubject 0x0000 // PT_UNICODE
#define PidNameTemplate 0x0000 // PT_UNICODE
#define PidNameTitle 0x0000 // PT_UNICODE
#define PidNameWordCount 0x0000 // PT_I4
#define PidNameAcceptLanguage 0x0000 // PT_UNICODE
#define PidNameApproved 0x0000 // PT_UNICODE
#define PidNameContentBase 0x0000 // PT_UNICODE
#define PidNameContentClass 0x0000 // PT_UNICODE
#define PidNameContentDisposition 0x0000 // PT_UNICODE
#define PidNameContentID 0x0000 // PT_UNICODE
#define PidNameContentLanguage 0x0000 // PT_UNICODE
#define PidNameContentLocation 0x0000 // PT_UNICODE
#define PidNameContentTransferEncoding 0x0000 // PT_UNICODE
#define PidNameContentType 0x0000 // PT_UNICODE
#define PidNameCrossReference 0x0000 // PT_UNICODE
#define PidNameXMSExchangeOrganizationAuthdomain 0x0000 // PT_UNICODE
#define PidNameXSharingBrowseUrl 0x0000 // PT_UNICODE
#define PidNameXSharingCapabilities 0x0000 // PT_UNICODE
#define PidNameXSharingConfigUrl 0x0000 // PT_UNICODE
#define PidNameXSharingFlavor 0x0000 // PT_UNICODE
#define PidNameXSharingInstanceGuid 0x0000 // PT_UNICODE
#define PidNameXSharingLocalType 0x0000 // PT_UNICODE
#define PidNameXSharingProviderGuid 0x0000 // PT_UNICODE
#define PidNameXSharingProviderName 0x0000 // PT_UNICODE
#define PidNameXSharingProviderUrl 0x0000 // PT_UNICODE
#define PidNameXSharingRemoteName 0x0000 // PT_UNICODE
#define PidNameXSharingRemotePath 0x0000 // PT_UNICODE
#define PidNameXSharingRemoteStoreUid 0x0000 // PT_UNICODE
#define PidNameXSharingRemoteType 0x0000 // PT_UNICODE
#define PidNameXSharingRemoteUid 0x0000 // PT_UNICODE
#define PidNameXSieve 0x0000 // PT_UNICODE
#define PidNameXVirusScanned 0x0000 // PT_UNICODE

/** PSETID_TASK */
#define PidLidTaskStatus 0x8101 // PT_I4
#define PidLidPercentComplete 0x8102 // PT_DOUBLE
#define PidLidTeamTask 0x8103 // PT_BOOLEAN
#define PidLidTaskStartDate 0x8104 // PT_SYSTIME
#define PidLidTaskDueDate 0x8105 // PT_SYSTIME
#define PidLidTaskResetReminder 0x8107 // PT_BOOLEAN
#define PidLidTaskAccepted 0x8108 // PT_BOOLEAN
#define PidLidTaskDeadOccurrence 0x8109 // PT_BOOLEAN
#define PidLidTaskDateCompleted 0x810F // PT_SYSTIME
#define PidLidTaskActualEffort 0x8110 // PT_I4
#define PidLidTaskEstimatedEffort 0x8111 // PT_I4
#define PidLidTaskVersion 0x8112 // PT_I4
#define PidLidTaskState 0x8113 // PT_I4
#define PidLidTaskLastUpdate 0x8115 // PT_SYSTIME
#define PidLidTaskRecurrence 0x8116 // PT_BINARY
#define PidLidTaskAssigners 0x8117 // PT_BINARY
#define PidLidTaskStatusOnComplete 0x8119 // PT_BOOLEAN
#define PidLidTaskHistory 0x811A // PT_I4
#define PidLidTaskUpdates 0x811B // PT_BOOLEAN
#define PidLidTaskComplete 0x811C // PT_BOOLEAN
#define PidLidTaskFCreator 0x811E // PT_BOOLEAN
#define PidLidTaskOwner_W 0x811F // PT_UNICODE
#define PidLidTaskOwner_A 0x811F // PT_STRING8

#define PidLidTaskMultipleRecipients 0x8120 // PT_I4
#define PidLidTaskAssigner_W 0x8121 // PT_UNICODE
#define PidLidTaskAssigner_A 0x8121 // PT_STRING8

#define PidLidTaskLastUser_W 0x8122 // PT_UNICODE
#define PidLidTaskLastUser_A 0x8122 // PT_STRING8

#define PidLidTaskOrdinal 0x8123 // PT_I4
#define PidLidTaskNoCompute 0x8124 // PT_BOOLEAN
#define PidLidTaskLastDelegate_W 0x8125 // PT_UNICODE
#define PidLidTaskLastDelegate_A 0x8125 // PT_STRING8

#define PidLidTaskFRecurring 0x8126 // PT_BOOLEAN
#define PidLidTaskRole_W 0x8127 // PT_UNICODE
#define PidLidTaskRole_A 0x8127 // PT_STRING8

#define PidLidTaskOwnership 0x8129 // PT_I4
#define PidLidAcceptanceState 0x812A // PT_I4
#define PidLidTaskFFixOffline 0x812C // PT_BOOLEAN
#define PidLidTaskCustomFlags 0x8139 // PT_I4

/** PSETID_COMMON */
#define PidLidDayOfMonth 0x1000 // PT_I4
#define PidLidICalendarDayOfWeekMask 0x1001 // PT_I4
#define PidLidOccurrences 0x1005 // PT_I4
#define PidLidMonthOfYear 0x1006 // PT_I4
#define PidLidNoEndDateFlag 0x100B // PT_BOOLEAN
#define PidLidRecurrenceDuration 0x100D // PT_I4
#define PidLidReminderDelta 0x8501 // PT_I4
#define PidLidReminderTime 0x8502 // PT_SYSTIME
#define PidLidReminderSet 0x8503 // PT_BOOLEAN
#define PidLidReminderTimeTime 0x8504 // PT_SYSTIME
#define PidLidReminderTimeDate 0x8505 // PT_SYSTIME
#define PidLidPrivate 0x8506 // PT_BOOLEAN
#define PidLidAgingDontAgeMe 0x850E // PT_BOOLEAN
#define PidLidSideEffects 0x8510 // PT_I4
#define PidLidRemoteStatus 0x8511 // PT_I4
#define PidLidSmartNoAttach 0x8514 // PT_BOOLEAN
#define PidLidCommonStart 0x8516 // PT_SYSTIME
#define PidLidCommonEnd 0x8517 // PT_SYSTIME
#define PidLidTaskMode 0x8518 // PT_I4
#define PidLidTaskGlobalId 0x8519 // PT_BINARY
#define PidLidAutoProcessState 0x851A // PT_I4
#define PidLidReminderOverride 0x851C // PT_BOOLEAN
#define PidLidReminderType 0x851D // PT_I4
#define PidLidReminderPlaySound 0x851E // PT_BOOLEAN
#define PidLidReminderFileParameter_W 0x851F // PT_UNICODE
#define PidLidReminderFileParameter_A 0x851F // PT_STRING8

#define PidLidVerbStream 0x8520 // PT_BINARY
#define PidLidVerbResponse_W 0x8524 // PT_UNICODE
#define PidLidVerbResponse_A 0x8524 // PT_STRING8

#define PidLidFlagRequest_W 0x8530 // PT_UNICODE
#define PidLidFlagRequest_A 0x8530 // PT_STRING8

#define PidLidMileage_W 0x8534 // PT_UNICODE
#define PidLidMileage_A 0x8534 // PT_STRING8

#define PidLidBillingInformation_W 0x8535 // PT_UNICODE
#define PidLidBillingInformation_A 0x8535 // PT_STRING8

#define PidLidNonSendtableTo_W 0x8536 // PT_UNICODE
#define PidLidNonSendtableTo_A 0x8536 // PT_STRING8

#define PidLidNonSendableCc_W 0x8537 // PT_UNICODE
#define PidLidNonSendableCc_A 0x8537 // PT_STRING8

#define PidLidNonSendableBcc_W 0x8538 // PT_UNICODE
#define PidLidNonSendableBcc_A 0x8538 // PT_STRING8

#define PidLidCompanies 0x8539 // PT_MV_STRING8
#define PidLidContacts 0x853A // PT_MV_STRING8
#define PidLidNonSendToTrackStatus 0x8543 // PT_MV_LONG
#define PidLidNonSendCcTrackStatus 0x8544 // PT_MV_LONG
#define PidLidNonSendBccTrackStatus 0x8545 // PT_MV_LONG
#define PidLidCurrentVersion 0x8552 // PT_I4
#define PidLidCurrentVersionName_W 0x8554 // PT_UNICODE
#define PidLidCurrentVersionName_A 0x8554 // PT_STRING8

#define PidLidReminderSignalTime 0x8560 // PT_SYSTIME
#define PidLidImapDeleted 0x8570 // PT_I4
#define PidLidHeaderItem 0x8578 // PT_I4
#define PidLidInternetAccountName_W 0x8580 // PT_UNICODE
#define PidLidInternetAccountName_A 0x8580 // PT_STRING8

#define PidLidInternetAccountStamp_W 0x8581 // PT_UNICODE
#define PidLidInternetAccountStamp_A 0x8581 // PT_STRING8

#define PidLidUseTnef 0x8582 // PT_BOOLEAN
#define PidLidContactLinkSearchKey 0x8584 // PT_BINARY
#define PidLidContactLinkEntry 0x8585 // PT_BINARY
#define PidLidContactLinkName_W 0x8586 // PT_UNICODE
#define PidLidContactLinkName_A 0x8586 // PT_STRING8

#define PidLidSpamOriginalFolder 0x859C // PT_BINARY
#define PidLidToDoOrdinalDate 0x85A0 // PT_SYSTIME
#define PidLidToDoSubOrdinal_W 0x85A1 // PT_UNICODE
#define PidLidToDoSubOrdinal_A 0x85A1 // PT_STRING8

#define PidLidToDoTitle_W 0x85A4 // PT_UNICODE
#define PidLidToDoTitle_A 0x85A4 // PT_STRING8

#define PidLidInfoPathFormName_W 0x85B1 // PT_UNICODE
#define PidLidInfoPathFormName_A 0x85B1 // PT_STRING8

#define PidLidClassified 0x85B5 // PT_BOOLEAN
#define PidLidClassification_W 0x85B6 // PT_UNICODE
#define PidLidClassification_A 0x85B6 // PT_STRING8

#define PidLidClassificationDescription_W 0x85B7 // PT_UNICODE
#define PidLidClassificationDescription_A 0x85B7 // PT_STRING8

#define PidLidClassificationGuid_W 0x85B8 // PT_UNICODE
#define PidLidClassificationGuid_A 0x85B8 // PT_STRING8

#define PidLidClassificationKeep 0x85BA // PT_BOOLEAN
#define PidLidReferenceEntryId 0x85BD // PT_BINARY
#define PidLidValidFlagStringProof 0x85BF // PT_SYSTIME
#define PidLidFlagString 0x85C0 // PT_I4
#define PidLidConversationActionMoveFolderEid 0x85C6 // PT_BINARY
#define PidLidConversationActionMoveStoreEid 0x85C7 // PT_BINARY
#define PidLidConversationActionMaxDeliveryTime 0x85C8 // PT_SYSTIME
#define PidLidConversationProcessed 0x85C9 // PT_I4
#define PidLidConversationActionLastAppliedTime 0x85CA // PT_SYSTIME
#define PidLidConversationActionVersion 0x85CB // PT_I4

/** PS_INTERNET_HEADERS (all use MNID_STRING and have propID 0x0000) */
#define PidNameBcc 0x0000 // PT_UNICODE

/** PSETID_SHARING */
#define PidLidSharingStatus 0x8A00 // PT_I4
#define PidLidSharingProviderGuid 0x8A01 // PT_BINARY
#define PidLidSharingProviderName_W 0x8A02 // PT_UNICODE
#define PidLidSharingProviderName_A 0x8A02 // PT_STRING8

#define PidLidSharingProviderUrl_W 0x8A03 // PT_UNICODE
#define PidLidSharingProviderUrl_A 0x8A03 // PT_STRING8

#define PidLidSharingRemotePath_W 0x8A04 // PT_UNICODE
#define PidLidSharingRemotePath_A 0x8A04 // PT_STRING8

#define PidLidSharingRemoteName_W 0x8A05 // PT_UNICODE
#define PidLidSharingRemoteName_A 0x8A05 // PT_STRING8

#define PidLidSharingRemoteUid_W 0x8A06 // PT_UNICODE
#define PidLidSharingRemoteUid_A 0x8A06 // PT_STRING8

#define PidLidSharingInitiatorName_W 0x8A07 // PT_UNICODE
#define PidLidSharingInitiatorName_A 0x8A07 // PT_STRING8

#define PidLidSharingInitiatorSmtp_W 0x8A08 // PT_UNICODE
#define PidLidSharingInitiatorSmtp_A 0x8A08 // PT_STRING8

#define PidLidSharingInitiatorEntryId 0x8A09 // PT_BINARY
#define PidLidSharingFlags 0x8A0A // PT_I4
#define PidLidSharingProviderExtension_W 0x8A0B // PT_UNICODE
#define PidLidSharingProviderExtension_A 0x8A0B // PT_STRING8

#define PidLidSharingRemoteUser_W 0x8A0C // PT_UNICODE
#define PidLidSharingRemoteUser_A 0x8A0C // PT_STRING8

#define PidLidSharingRemotePass_W 0x8A0D // PT_UNICODE
#define PidLidSharingRemotePass_A 0x8A0D // PT_STRING8

#define PidLidSharingLocalPath_W 0x8A0E // PT_UNICODE
#define PidLidSharingLocalPath_A 0x8A0E // PT_STRING8

#define PidLidSharingLocalName_W 0x8A0F // PT_UNICODE
#define PidLidSharingLocalName_A 0x8A0F // PT_STRING8

#define PidLidSharingLocalUid_W 0x8A10 // PT_UNICODE
#define PidLidSharingLocalUid_A 0x8A10 // PT_STRING8

#define PidLidSharingFilter 0x8A13 // PT_BINARY
#define PidLidSharingLocalType_W 0x8A14 // PT_UNICODE
#define PidLidSharingLocalType_A 0x8A14 // PT_STRING8

#define PidLidSharingFolderEntryId 0x8A15 // PT_BINARY
#define PidLidSharingCapabilities 0x8A17 // PT_I4
#define PidLidSharingFlavor 0x8A18 // PT_I4
#define PidLidSharingAnonymity 0x8A19 // PT_I4
#define PidLidSharingReciprocation 0x8A1A // PT_I4
#define PidLidSharingPermissions 0x8A1B // PT_I4
#define PidLidSharingInstanceGuid 0x8A1C // PT_BINARY
#define PidLidSharingRemoteType_W 0x8A1D // PT_UNICODE
#define PidLidSharingRemoteType_A 0x8A1D // PT_STRING8

#define PidLidSharingParticipants_W 0x8A1E // PT_UNICODE
#define PidLidSharingParticipants_A 0x8A1E // PT_STRING8

#define PidLidSharingLastSyncTime 0x8A1F // PT_SYSTIME
#define PidLidSharingExtensionXml_W 0x8A21 // PT_UNICODE
#define PidLidSharingExtensionXml_A 0x8A21 // PT_STRING8

#define PidLidSharingRemoteLastModificationTime 0x8A22 // PT_SYSTIME
#define PidLidSharingLocalLastModificationTime 0x8A23 // PT_SYSTIME
#define PidLidSharingConfigurationUrl_W 0x8A24 // PT_UNICODE
#define PidLidSharingConfigurationUrl_A 0x8A24 // PT_STRING8

#define PidLidSharingStart 0x8A25 // PT_SYSTIME
#define PidLidSharingStop 0x8A26 // PT_SYSTIME
#define PidLidSharingResponseType 0x8A27 // PT_I4
#define PidLidSharingResponseTime 0x8A28 // PT_SYSTIME
#define PidLidSharingOriginalMessageEntryId 0x8A29 // PT_BINARY
#define PidLidSharingSyncInterval 0x8A2A // PT_I4
#define PidLidSharingDetail 0x8A2B // PT_I4
#define PidLidSharingTimeToLive 0x8A2C // PT_I4
#define PidLidSharingBindingEntryId 0x8A2D // PT_BINARY
#define PidLidSharingIndexEntryId 0x8A2E // PT_BINARY
#define PidLidSharingRemoteComment_W 0x8A2F // PT_UNICODE
#define PidLidSharingRemoteComment_A 0x8A2F // PT_STRING8

#define PidLidSharingWorkingHoursStart 0x8A40 // PT_SYSTIME
#define PidLidSharingWorkingHoursEnd 0x8A41 // PT_SYSTIME
#define PidLidSharingWorkingHoursDay 0x8A42 // PT_I4
#define PidLidSharingWorkingHoursTimeZone 0x8A43 // PT_BINARY
#define PidLidSharingDataRangeStart 0x8A44 // PT_SYSTIME
#define PidLidSharingDataRangeEnd 0x8A45 // PT_SYSTIME
#define PidLidSharingRangeStart 0x8A46 // PT_I4
#define PidLidSharingRangeEnd 0x8A47 // PT_I4
#define PidLidSharingRemoteStoreUid_W 0x8A48 // PT_UNICODE
#define PidLidSharingRemoteStoreUid_A 0x8A48 // PT_STRING8

#define PidLidSharingLocalStoreUid_W 0x8A49 // PT_UNICODE
#define PidLidSharingLocalStoreUid_A 0x8A49 // PT_STRING8

#define PidLidSharingRemoteByteSize 0x8A4B // PT_I4
#define PidLidSharingRemoteCrc 0x8A4C // PT_I4
#define PidLidSharingLocalComment_W 0x8A4D // PT_UNICODE
#define PidLidSharingLocalComment_A 0x8A4D // PT_STRING8

#define PidLidSharingRoamLog 0x8A4E // PT_I4
#define PidLidSharingRemoteMessageCount 0x8A4F // PT_I4
#define PidLidSharingBrowseUrl_W 0x8A51 // PT_UNICODE
#define PidLidSharingBrowseUrl_A 0x8A51 // PT_STRING8

#define PidLidSharingLastAutoSyncTime 0x8A55 // PT_SYSTIME
#define PidLidSharingTimeToLiveAuto 0x8A56 // PT_I4
#define PidLidSharingRemoteVersion_W 0x8A5B // PT_UNICODE
#define PidLidSharingRemoteVersion_A 0x8A5B // PT_STRING8

#define PidLidSharingParentBindingEntryId 0x8A5C // PT_BINARY
#define PidLidSharingSyncFlags 0x8A60 // PT_I4

/** PSETID_ADDRESS */
#define PidLidFileUnder_W 0x8005 // PT_UNICODE
#define PidLidFileUnder_A 0x8005 // PT_STRING8

#define PidLidFileUnderId 0x8006 // PT_I4
#define PidLidContactItemData 0x8007 // PT_MV_LONG
#define PidLidReferredBy_W 0x800E // PT_UNICODE
#define PidLidReferredBy_A 0x800E // PT_STRING8

#define PidLidDepartment_W 0x8010 // PT_UNICODE
#define PidLidDepartment_A 0x8010 // PT_STRING8

#define PidLidHasPicture 0x8015 // PT_BOOLEAN
#define PidLidHomeAddress_W 0x801A // PT_UNICODE
#define PidLidHomeAddress_A 0x801A // PT_STRING8

#define PidLidWorkAddress_W 0x801B // PT_UNICODE
#define PidLidWorkAddress_A 0x801B // PT_STRING8

#define PidLidOtherAddress_W 0x801C // PT_UNICODE
#define PidLidOtherAddress_A 0x801C // PT_STRING8

#define PidLidPostalAddressId 0x8022 // PT_I4
#define PidLidContactCharacterSet 0x8023 // PT_I4
#define PidLidAutoLog 0x8025 // PT_BOOLEAN
#define PidLidFileUnderList 0x8026 // PT_MV_LONG
#define PidLidEmailList 0x8027 // PT_MV_LONG
#define PidLidAddressBookProviderEmailList 0x8028 // PT_MV_LONG
#define PidLidAddressBookProviderArrayType 0x8029 // PT_I4
#define PidLidHtml_W 0x802B // PT_UNICODE
#define PidLidHtml_A 0x802B // PT_STRING8

#define PidLidYomiFirstName_W 0x802C // PT_UNICODE
#define PidLidYomiFirstName_A 0x802C // PT_STRING8

#define PidLidYomiLastName_W 0x802D // PT_UNICODE
#define PidLidYomiLastName_A 0x802D // PT_STRING8

#define PidLidYomiCompanyName_W 0x802E // PT_UNICODE
#define PidLidYomiCompanyName_A 0x802E // PT_STRING8

#define PidLidBusinessCardDisplayDefinition 0x8040 // PT_BINARY
#define PidLidBusinessCardCardPicture 0x8041 // PT_BINARY
#define PidLidWorkAddressStreet_W 0x8045 // PT_UNICODE
#define PidLidWorkAddressStreet_A 0x8045 // PT_STRING8

#define PidLidWorkAddressCity_W 0x8046 // PT_UNICODE
#define PidLidWorkAddressCity_A 0x8046 // PT_STRING8

#define PidLidWorkAddressState_W 0x8047 // PT_UNICODE
#define PidLidWorkAddressState_A 0x8047 // PT_STRING8

#define PidLidWorkAddressPostalCode_W 0x8048 // PT_UNICODE
#define PidLidWorkAddressPostalCode_A 0x8048 // PT_STRING8

#define PidLidWorkAddressCountry_W 0x8049 // PT_UNICODE
#define PidLidWorkAddressCountry_A 0x8049 // PT_STRING8

#define PidLidWorkAddressPostOfficeBox_W 0x804A // PT_UNICODE
#define PidLidWorkAddressPostOfficeBox_A 0x804A // PT_STRING8

#define PidLidDistributionListChecksum 0x804C // PT_I4
#define PidLidBirthdayEventEntryId 0x804D // PT_BINARY
#define PidLidAnniversaryEventEntryId 0x804E // PT_BINARY
#define PidLidContactUserField1_W 0x804F // PT_UNICODE
#define PidLidContactUserField1_A 0x804F // PT_STRING8

#define PidLidContactUserField2_W 0x8050 // PT_UNICODE
#define PidLidContactUserField2_A 0x8050 // PT_STRING8

#define PidLidContactUserField3_W 0x8051 // PT_UNICODE
#define PidLidContactUserField3_A 0x8051 // PT_STRING8

#define PidLidContactUserField4_W 0x8052 // PT_UNICODE
#define PidLidContactUserField4_A 0x8052 // PT_STRING8

#define PidLidDistributionListName_W 0x8053 // PT_UNICODE
#define PidLidDistributionListName_A 0x8053 // PT_STRING8

#define PidLidDistributionListOneOffMembers 0x8054 // PT_MV_BINARY
#define PidLidDistributionListMembers 0x8055 // PT_MV_BINARY
#define PidLidInstantMessagingAddress_W 0x8062 // PT_UNICODE
#define PidLidInstantMessagingAddress_A 0x8062 // PT_STRING8

#define PidLidDistributionListStream 0x8064 // PT_I4
#define PidLidEmail1DisplayName_W 0x8080 // PT_UNICODE
#define PidLidEmail1DisplayName_A 0x8080 // PT_STRING8

#define PidLidEmail1AddressType_W 0x8082 // PT_UNICODE
#define PidLidEmail1AddressType_A 0x8082 // PT_STRING8

#define PidLidEmail1EmailAddress_W 0x8083 // PT_UNICODE
#define PidLidEmail1EmailAddress_A 0x8083 // PT_STRING8

#define PidLidEmail1OriginalDisplayName_W 0x8084 // PT_UNICODE
#define PidLidEmail1OriginalDisplayName_A 0x8084 // PT_STRING8

#define PidLidEmail1OriginalEntryId 0x8085 // PT_BINARY
#define PidLidEmail1RichTextFormat 0x8086 // PT_BOOLEAN
#define PidLidEmail1EmailType_W 0x8087 // PT_UNICODE
#define PidLidEmail1EmailType_A 0x8087 // PT_STRING8

#define PidLidEmail2DisplayName_W 0x8090 // PT_UNICODE
#define PidLidEmail2DisplayName_A 0x8090 // PT_STRING8

#define PidLidEmail2EntryId 0x8091 // PT_BINARY
#define PidLidEmail2AddressType_W 0x8092 // PT_UNICODE
#define PidLidEmail2AddressType_A 0x8092 // PT_STRING8

#define PidLidEmail2EmailAddress_W 0x8093 // PT_UNICODE
#define PidLidEmail2EmailAddress_A 0x8093 // PT_STRING8

#define PidLidEmail2OriginalDisplayName_W 0x8094 // PT_UNICODE
#define PidLidEmail2OriginalDisplayName_A 0x8094 // PT_STRING8

#define PidLidEmail2OriginalEntryId 0x8095 // PT_BINARY
#define PidLidEmail2RichTextFormat 0x8096 // PT_BOOLEAN
#define PidLidEmail3DisplayName_W 0x80A0 // PT_UNICODE
#define PidLidEmail3DisplayName_A 0x80A0 // PT_STRING8

#define PidLidEmail3EntryId 0x80A1 // PT_BINARY
#define PidLidEmail3AddressType_W 0x80A2 // PT_UNICODE
#define PidLidEmail3AddressType_A 0x80A2 // PT_STRING8

#define PidLidEmail3EmailAddress_W 0x80A3 // PT_UNICODE
#define PidLidEmail3EmailAddress_A 0x80A3 // PT_STRING8

#define PidLidEmail3OriginalDisplayName_W 0x80A4 // PT_UNICODE
#define PidLidEmail3OriginalDisplayName_A 0x80A4 // PT_STRING8

#define PidLidEmail3OriginalEntryId 0x80A5 // PT_BINARY
#define PidLidEmail3RichTextFormat 0x80A6 // PT_BOOLEAN
#define PidLidFax1AddressType_W 0x80B2 // PT_UNICODE
#define PidLidFax1AddressType_A 0x80B2 // PT_STRING8

#define PidLidFax1EmailAddress_W 0x80B3 // PT_UNICODE
#define PidLidFax1EmailAddress_A 0x80B3 // PT_STRING8

#define PidLidFax1OriginalDisplayName_W 0x80B4 // PT_UNICODE
#define PidLidFax1OriginalDisplayName_A 0x80B4 // PT_STRING8

#define PidLidFax1OriginalEntryId 0x80B5 // PT_BINARY
#define PidLidFax2AddressType_W 0x80C2 // PT_UNICODE
#define PidLidFax2AddressType_A 0x80C2 // PT_STRING8

#define PidLidFax2EmailAddress_W 0x80C3 // PT_UNICODE
#define PidLidFax2EmailAddress_A 0x80C3 // PT_STRING8

#define PidLidFax2OriginalDisplayName_W 0x80C4 // PT_UNICODE
#define PidLidFax2OriginalDisplayName_A 0x80C4 // PT_STRING8

#define PidLidFax2OriginalEntryId 0x80C5 // PT_BINARY
#define PidLidFax3AddressType_W 0x80D2 // PT_UNICODE
#define PidLidFax3AddressType_A 0x80D2 // PT_STRING8

#define PidLidFax3EmailAddress_W 0x80D3 // PT_UNICODE
#define PidLidFax3EmailAddress_A 0x80D3 // PT_STRING8

#define PidLidFax3OriginalDisplayName_W 0x80D4 // PT_UNICODE
#define PidLidFax3OriginalDisplayName_A 0x80D4 // PT_STRING8

#define PidLidFax3OriginalEntryId 0x80D5 // PT_BINARY
#define PidLidFreeBusyLocation_W 0x80D8 // PT_UNICODE
#define PidLidFreeBusyLocation_A 0x80D8 // PT_STRING8

#define PidLidHomeAddressCountryCode_W 0x80DA // PT_UNICODE
#define PidLidHomeAddressCountryCode_A 0x80DA // PT_STRING8

#define PidLidWorkAddressCountryCode_W 0x80DB // PT_UNICODE
#define PidLidWorkAddressCountryCode_A 0x80DB // PT_STRING8

#define PidLidOtherAddressCountryCode_W 0x80DC // PT_UNICODE
#define PidLidOtherAddressCountryCode_A 0x80DC // PT_STRING8

#define PidLidAddressCountryCode_W 0x80DD // PT_UNICODE
#define PidLidAddressCountryCode_A 0x80DD // PT_STRING8

/** PSETID_MEETING */
#define PidLidAttendeeCriticalChange 0x0001 // PT_SYSTIME
#define PidLidWhere_W 0x0002 // PT_UNICODE
#define PidLidWhere_A 0x0002 // PT_STRING8

#define PidLidGlobalObjectId 0x0003 // PT_BINARY
#define PidLidIsSilent 0x0004 // PT_BOOLEAN
#define PidLidIsRecurring 0x0005 // PT_BOOLEAN
#define PidLidRequiredAttendees_W 0x0006 // PT_UNICODE
#define PidLidRequiredAttendees_A 0x0006 // PT_STRING8

#define PidLidOptionalAttendees_W 0x0007 // PT_UNICODE
#define PidLidOptionalAttendees_A 0x0007 // PT_STRING8

#define PidLidResourceAttendees_W 0x0008 // PT_UNICODE
#define PidLidResourceAttendees_A 0x0008 // PT_STRING8

#define PidLidDelegateMail 0x0009 // PT_BOOLEAN
#define PidLidIsException 0x000A // PT_BOOLEAN
#define PidLidSingleInvite 0x000B // PT_BOOLEAN
#define PidLidTimeZone 0x000C // PT_I4
#define PidLidStartRecurrenceDate 0x000D // PT_I4
#define PidLidStartRecurrenceTime 0x000E // PT_I4
#define PidLidEndRecurrenceDate 0x000F // PT_I4
#define PidLidEndRecurrenceTime 0x0010 // PT_I4
#define PidLidDayInterval 0x0011 // PT_I2
#define PidLidWeekInterval 0x0012 // PT_I2
#define PidLidMonthInterval 0x0013 // PT_I2
#define PidLidYearInterval 0x0014 // PT_I2
#define PidLidMonthOfYearMask 0x0017 // PT_I4
#define PidLidOldRecurrenceType 0x0018 // PT_I2
#define PidLidOwnerCriticalChange 0x001A // PT_SYSTIME
#define PidLidCalendarType 0x001C // PT_I4
#define PidLidAllAttendeesList_W 0x001D // PT_UNICODE
#define PidLidAllAttendeesList_A 0x001D // PT_STRING8

#define PidLidCleanGlobalObjectId 0x0023 // PT_BINARY
#define PidLidAppointmentMessageClass_W 0x0024 // PT_UNICODE
#define PidLidAppointmentMessageClass_A 0x0024 // PT_STRING8

#define PidLidMeetingType 0x0026 // PT_I4
#define PidLidOldLocation_W 0x0028 // PT_UNICODE
#define PidLidOldLocation_A 0x0028 // PT_STRING8

#define PidLidOldWhenStartWhole 0x0029 // PT_SYSTIME
#define PidLidOldWhenEndWhole 0x002A // PT_SYSTIME

/** PSETID_LOG */
#define PidLidLogType_W 0x8700 // PT_UNICODE
#define PidLidLogType_A 0x8700 // PT_STRING8

#define PidLidLogStart 0x8706 // PT_SYSTIME
#define PidLidLogDuration 0x8707 // PT_I4
#define PidLidLogEnd 0x8708 // PT_SYSTIME
#define PidLidLogFlags 0x870C // PT_I4
#define PidLidDocumentPrinted 0x870E // PT_BOOLEAN
#define PidLidDocumentSaved 0x870F // PT_BOOLEAN
#define PidLidDocumentRouted 0x8710 // PT_BOOLEAN
#define PidLidDocumentPosted 0x8711 // PT_BOOLEAN
#define PidLidLogTypeDesc_W 0x8712 // PT_UNICODE
#define PidLidLogTypeDesc_A 0x8712 // PT_STRING8

/** PSETID_POSTRSS */
#define PidLidPostRssChannelLink_W 0x8900 // PT_UNICODE
#define PidLidPostRssChannelLink_A 0x8900 // PT_STRING8

#define PidLidPostRssItemLink_W 0x8901 // PT_UNICODE
#define PidLidPostRssItemLink_A 0x8901 // PT_STRING8

#define PidLidPostRssItemHash 0x8902 // PT_I4
#define PidLidPostRssItemGuid_W 0x8903 // PT_UNICODE
#define PidLidPostRssItemGuid_A 0x8903 // PT_STRING8

#define PidLidPostRssChannel_W 0x8904 // PT_UNICODE
#define PidLidPostRssChannel_A 0x8904 // PT_STRING8

#define PidLidPostRssItemXml_W 0x8905 // PT_UNICODE
#define PidLidPostRssItemXml_A 0x8905 // PT_STRING8

#define PidLidPostRssSubscription_W 0x8906 // PT_UNICODE
#define PidLidPostRssSubscription_A 0x8906 // PT_STRING8

/** PSETID_NOTE */
#define PidLidNoteColor 0x8B00 // PT_I4
#define PidLidNoteWidth 0x8B02 // PT_I4
#define PidLidNoteHeight 0x8B03 // PT_I4
#define PidLidNoteX 0x8B04 // PT_I4
#define PidLidNoteY 0x8B05 // PT_I4

/** PSETID_CALENDARASSISTANT */
#define PidLidClientIntent 0x0015 // PT_I4
#define PidLidServerProcessed 0x85CC // PT_BOOLEAN
#define PidLidServerProcessingActions 0x85CD // PT_I4

/** PSETID_REMOTE */
#define PidLidRemoteTransferSize 0x8f05 // PT_I4
#define PidLidRemoteAttachment 0x8f07 // PT_BOOLEAN

#endif /* MAPITAGS_H */
